### ISSUE TITLE
Segmentation Fault when comparing two databases

### ISSUE THREAD

**Issue by bordin89** [steineggerlab/foldseek#1]
## Expected Behavior

I'm currently trying to align a database with 23391 structures against a dabase of CATH s35 PDB files in an all vs all fashion.

## Current Behavior
Segmentation fault at line 17 structureresearch.sh

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders. - Done
Generated with createdb successfully, empty tmp folder. 
Launched as `programs/foldseek/bin/foldseek search species/foldseek_db/homo_sapiens cath_s35_scans/s35_database cath_s35_scans/results/homo_sapiens_s35.m8 tmp`

The two databases show as complete, although the program fails at 
`tmp/11743319497277053650/structuresearch.sh: line 17: 56940 Segmentation fault      $RUNNER "$MMSEQS" prefilter "${QUERY_PREFILTER}" "${TARGET_PREFILTER}${INDEXEXT}" "${TMP_PATH}/pref" ${PREFILTER_PAR}`
`Error: Kmer matching step died`

Here is the full output 

```
programs/foldseek/bin/foldseek search species/foldseek_db/homo_sapiens cath_s35_scans/s35_database cath_s35_scans/results/homo_sapiens_s35.m8 tmp
cath_s35_scans/results/homo_sapiens_s35.m8 exists and will be overwritten
Create directory tmp
search species/foldseek_db/homo_sapiens cath_s35_scans/s35_database cath_s35_scans/results/homo_sapiens_s35.m8 tmp

MMseqs Version:                 75bb2e3a2718903f47008d7d8cc3be099e35d1e9
Seq. id. threshold              0
Coverage threshold              0
Coverage mode                   0
Max reject                      2147483647
Max accept                      2147483647
Add backtrace                   false
Include identical seq. id.      false
TMscore threshold               0.5
Threads                         48
Verbosity                       3
Substitution matrix             nucl:3di.out,aa:3di.out
Alignment mode                  3
Alignment mode                  0
Allow wrapped scoring           false
E-value threshold               0.001
Min alignment length            0
Seq. id. mode                   0
Alternative alignments          0
Max sequence length             65535
Compositional bias              0
Preload mode                    0
Pseudo count a                  1
Pseudo count b                  1.5
Score bias                      0
Realign hits                    false
Realign score bias              -0.2
Realign max seqs                2147483647
Gap open cost                   nucl:5,aa:11
Gap extension cost              nucl:2,aa:1
Zdrop                           40
Compressed                      0
Seed substitution matrix        nucl:3di.out,aa:3di.out
Sensitivity                     7.5
k-mer length                    0
k-score                         2147483647
Alphabet size                   nucl:5,aa:21
Max results per query           300
Split database                  0
Split mode                      2
Split memory limit              0
Diagonal scoring                true
Exact k-mer matching            0
Mask residues                   0
Mask lower case residues        0
Minimum diagonal score          15
Spaced k-mers                   1
Spaced k-mer pattern
Local temporary path
Alignment type                  0

prefilter species/foldseek_db/homo_sapiens_ss cath_s35_scans/s35_database_ss tmp/11743319497277053650/pref --sub-mat nucl:3di.out,aa:3di.out --seed-sub-mat nucl:3di.out,aa:3di.out -s 7.5 -k 0 --k-score 2147483647 --alph-size nucl:5,aa:21 --max-seq-len 65535 --max-seqs 300 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 0 --diag-score 1 --exact-kmer-matching 0 --mask 0 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca 1 --pcb 1.5 --threads 48 --compressed 0 -v 3

Query database size: 23391 type: Aminoacid
Estimated memory consumption: 359M
Target database size: 32388 type: Aminoacid
Index table k-mer threshold: 96 at k-mer size 6
Index table: counting k-mers
[=================================================================] 100.00% 32.39K 0s 225ms
Index table: Masked residues: 0
Index table: fill
[=================================================================] 100.00% 32.39K 0s 261ms
Index statistics
Entries:          4390456
DB size:          153 MB
Avg k-mer size:   0.261692
Top 10 k-mers
    CCCCCC      1391
    PCCCKS      1141
    PCCCGI      1027
    CPPPCP      913
    PPPPPP      833
    IPPPPP      656
    MCCCKS      612
    CCCCCS      557
    CKKIPP      504
    PCCCHS      480
Time for index table init: 0h 0m 0s 965ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 96
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 23391
Target db start 1 to 32388
tmp/11743319497277053650/structuresearch.sh: line 17: 56940 Segmentation fault      $RUNNER "$MMSEQS" prefilter "${QUERY_PREFILTER}" "${TARGET_PREFILTER}${INDEXEXT}" "${TMP_PATH}/pref" ${PREFILTER_PAR}
Error: Kmer matching step died
```

## Context
If I use easy-search instead of search the first database shows a `Query database size: 0`

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute foldseek without any parameters): 75bb2e3a2718903f47008d7d8cc3be099e35d1e9
* Which foldseek version was used (Statically-compiled, self-compiled, Conda, etc.): statically-compiled (AVX2)
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation: N/A
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): CPU supports AVX2 and SSE2
* I ran this with 32G of RAM and 8 Threads
* Operating system and version: CentOS 7

Alternatively, can Foldseek run on all the structures contained within a folder?

Thank you for all your the great tools and work!

**Comment by bordin89** [comment]
I tried to feed the program with 1000 structures from the query database and it ran to completion. With 2000 structures it gets the same error. Could it be some missing flags or a lack of RAM on my end?

**Comment by martin-steinegger** [comment]
Thank you for reporting it. Could you please share your 2,000 structures that causes the error?

**Comment by bordin89** [comment]
Hi, Thank you for the quick reply! 

By running the data in chunks I managed to figure out which ones were the problematic PDB files. It boils down to 14 AlphaFold models for 2 proteins that are huge (M0QZD8 and P04114) with 3,266 and 4,563 residues.
I'm attaching two links to OneDrive with the structures and the database
Problematic structures https://liveuclac-my.sharepoint.com/:u:/g/personal/ucbtnb4_ucl_ac_uk/ETEYfojc9DRKhPyqRVOpAXEBfw6xkHOpTVYS46zbGctD5A?e=cRqNve 
Database: https://liveuclac-my.sharepoint.com/:u:/g/personal/ucbtnb4_ucl_ac_uk/EezQQjKSFppJsK3da9a6pCQB15lR6-4WSF_AZX_dSwaPug?e=RaAXsY

Is it possible to output in the log which structure in a set is breaking the run? 

Thanks again!

**Comment by martin-steinegger** [comment]
@bordin89 thank you so much for sharing the data. I ran foldseek with your example but it did not crash. Could you please try the newest version. I recently fixed a createdb bug, which might have cause the issue.

**Comment by martin-steinegger** [comment]
Does this issue still occur?

**Comment by bordin89** [comment]
No, the latest release of Foldseek seems to have fixed the issue. Thanks for the follow-up!
