### ISSUE TITLE
No matched results for simple short helix

### ISSUE THREAD

**Issue by KatarinaYuan** [steineggerlab/foldseek#105]
## Expected Behavior & Current Behavior
Hi, I have a demo helix structure and want to test it with FoldSeek. In theory, helix structure should quite common in AlphaFold2 database. But the search result is empty. However, when I change the demo pdb file to another protein PDB existing in the target AlphaFold2 database, it show me some matched proteins. Wondering if you have any suggestion? Thank you for your help!

### Target database
1. Download
The target dataset is from "AlphaFold2 reveals commonalities and novelties in protein structure space for 21 model organisms
" (https://www.nature.com/articles/s42003-023-04488-9), which can be downloaded from https://zenodo.org/record/7404988#.ZCUFuuyZNqt 

2. Create database
```
foldseek createdb ~/scratch/protein-datasets/by_superfamily/ ~/scratch/protein-datasets/cath_af2_by_superfamily/foldseek_database
```

### Search for demo.pdb (a single short helix)
```
foldseek easy-search ~/scratch/protein-datasets/demo.pdb ~/scratch/protein-datasets/cath_af2_by_superfamily/foldseek_database aln.m8 ~/scratch/protein-datasets/cath_af2_by_superfamily/foldseek_tmpFolder -s 9 --cov-mode 2 --format-output query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,alntmscore
```

The resulting file `aln.m8` is empty.

### Search for existing protein 

```
foldseek easy-search ~/scratch/protein-datasets/by_organism/staphylococcus_aureus/af_Q2FYZ1_1_77 ~/scratch/protein-datasets/cath_af2_by_superfamily/foldseek_database aln2.m8 ~/scratch/protein-datasets/cath_af2_by_superfamily/foldseek_tmpFolder -s 9 --cov-mode 2 --format-output query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,alntmscore
```

The resulting file `aln2.m8` is not empty and is attached below.
<img width="928" alt="Screen Shot 2023-04-09 at 12 02 11 AM" src="https://user-images.githubusercontent.com/43512683/230753619-255fa0bd-e842-411b-807b-eafb5e8672d3.png">

## The demo.pdb file 

[demo.pdb.zip](https://github.com/steineggerlab/foldseek/files/11184771/demo.pdb.zip)

**Comment by martin-steinegger** [comment]
The entire structure appears to be composed of glycine residues and, as you pointed out, forms a single helix. We utilize various strategies to suppress matching such structures, as they are typically considered non-homologous and regarded as false positives due to their compositional biases.

Nevertheless, you may still be able to align this structure using our TM-align mode. However, you will likely need to disable all the measures implemented to prevent false positives, such as compositional bias correction and masking. To accomplish this, include the following parameters in your search call:
```
foldseek easy-search demo.pdb foldseek_database aln tmp -e inf --comp-bias-corr 0 --mask 0 --alignment-type 1
```
If you still can not find the desired hits you can add the `--exhaustive-search` flag.

**Comment by KatarinaYuan** [comment]
Thank you for the great suggestion! After I use all the arguments you listed, the search result is not empty anymore.

Could you please clarify more about the "various strategies" to suppress the matching to be homologous? And what does it mean by "composition biases"? Could you make some examples? And what's the proper threshold for people to think the matched result can be viewed as "structurally similar" and "functionally similar"? 

(I'm still new to this bio area, thank you for the help!)

**Comment by martin-steinegger** [comment]
@KatarinaYuan, you can learn more about strategies to avoid high-scoring false positives in our Foldseek [preprint](https://www.biorxiv.org/content/10.1101/2022.02.07.479398v5). For further reading on compositional corrections, a good starting point is the work by [Altschul et al.](https://febs.onlinelibrary.wiley.com/doi/full/10.1111/j.1742-4658.2005.04945.x). The compositional bias correction strategy utilized in Foldseek is explained in detail in the [MMseqs](https://academic.oup.com/bioinformatics/article/32/9/1323/1744460) and [MMseqs2](https://www.nature.com/articles/nbt.3988) manuscripts.
