### ISSUE TITLE
python version code

### ISSUE THREAD

**Issue by ManlioWu** [steineggerlab/foldseek#106]
Hello! Could you provide the code of foldseek with python? Thanks!

**Comment by ManlioWu** [comment]
I want to train your model on other protein data, but cpp version code is diffcult for me. I'd appreciate it if you could provide the python one if you have it. Thanks a lot.

**Comment by martin-steinegger** [comment]
@ManlioWu I am not 100% sure what exactly you require, but our Python-based training code for the VQ-VAE is available [here](https://github.com/steineggerlab/foldseek-analysis).

**Comment by ManlioWu** [comment]
> @ManlioWu I am not 100% sure what exactly you require, but our Python-based training code for the VQ-VAE is available [here](https://github.com/steineggerlab/foldseek-analysis).

This is what I need. Thank you very much!
