### ISSUE TITLE
comapared to USalign?

### ISSUE THREAD

**Issue by BinhongLiu** [steineggerlab/foldseek#112]
## Expected Behavior
HI, 
    have you compared the speed of foldseek to that of USalign (https://www.nature.com/articles/s41592-022-01585-1) when compare protein structures? Which is faster when dealing with a huge dataset of protein structures?

**Comment by martin-steinegger** [comment]
USalign is a composite tool for aligners, which includes MMalign, TMalign, and others. Therefore, when comparing speed, you can use TMalign numbers as a reference benchmark.
