### ISSUE TITLE
No hits in aln.m8?

### ISSUE THREAD

**Issue by BinhongLiu** [steineggerlab/foldseek#113]
## Expected Behavior
I'd like to search a similar structure to AF-D2QBA9-F1-model_v3 within the PDB database. However, not results were produced. Why nothing reported in the aln.m8 file? If this is because no structures have been found that meet the similarity threshold, how can these low-similarity comparisons be output?

## Steps to Reproduce (for bugs)
`foldseek easy-search AF-D2QBA9-F1-model_v3.cif.gz /home/liuhongbin/database/FoldSeek/pdb100/pdb aln.m8 tmpFolder --exhaustive-search 1`

## Foldssek Output (for bugs)

easy-search AF-D2QBA9-F1-model_v3.cif.gz /home/liuhongbin/database/FoldSeek/pdb100/pdb aln.m8 tmpFolder --exhaustive-search 1 

MMseqs Version:                 5.53465f0
Seq. id. threshold              0
Coverage threshold              0
Coverage mode                   0
Max reject                      2147483647
Max accept                      2147483647
Add backtrace                   false
TMscore threshold               0
TMalign hit order               0
TMalign fast                    1
Preload mode                    0
Threads                         176
Verbosity                       3
LDDT threshold                  0
Sort by structure bit score     1
Substitution matrix             aa:3di.out,nucl:3di.out
Alignment mode                  3
Alignment mode                  0
E-value threshold               10
Min alignment length            0
Seq. id. mode                   0
Alternative alignments          0
Max sequence length             65535
Compositional bias              1
Compositional bias              1
Gap open cost                   aa:10,nucl:10
Gap extension cost              aa:1,nucl:1
Compressed                      0
Seed substitution matrix        aa:3di.out,nucl:3di.out
Sensitivity                     9.5
k-mer length                    6
k-score                         seq:2147483647,prof:2147483647
Max results per query           1000
Split database                  0
Split mode                      2
Split memory limit              0
Diagonal scoring                true
Exact k-mer matching            0
Mask residues                   0
Mask residues probability       0.99995
Mask lower case residues        1
Minimum diagonal score          15
Selected taxa                   
Spaced k-mers                   1
Spaced k-mer pattern            
Local temporary path            
Exhaustive search mode          true
Search iterations               1
Alignment type                  2
Remove temporary files          true
MPI runner                      
Force restart with latest tmp   false
Chain name mode                 0
Mask b-factor threshold         0
Coord store mode                2
Write lookup file               1
Tar Inclusion Regex             .*
Tar Exclusion Regex             ^$
Alignment format                0
Format alignment output         query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits
Database output                 false

createdb AF-D2QBA9-F1-model_v3.cif.gz tmpFolder/6144580022869075475/query --chain-name-mode 0 --mask-bfactor-threshold 0 --coord-store-mode 2 --write-lookup 1 --tar-include '.*' --tar-exclude '^$' --threads 176 -v 3 

Output file: tmpFolder/6144580022869075475/query
[=================================================================] 100.00% 1 eta -
Time for merging to query_ss: 0h 0m 0s 928ms
Time for merging to query_h: 0h 0m 0s 499ms
Time for merging to query_ca: 0h 0m 0s 588ms
Time for merging to query: 0h 0m 0s 481ms
Ignore 0 out of 1.
Too short: 0, incorrect  0.
Time for processing: 0h 0m 4s 125ms
Create directory tmpFolder/6144580022869075475/search_tmp
search tmpFolder/6144580022869075475/query /home/liuhongbin/database/FoldSeek/pdb100/pdb tmpFolder/6144580022869075475/result tmpFolder/6144580022869075475/search_tmp --alignment-mode 3 --comp-bias-corr 1 --gap-open aa:10,nucl:10 --gap-extend aa:1,nucl:1 -s 9.5 -k 6 --mask 0 --mask-prob 0.99995 --exhaustive-search 1 --remove-tmp-files 1 

structurealign tmpFolder/6144580022869075475/query /home/liuhongbin/database/FoldSeek/pdb100/pdb tmpFolder/6144580022869075475/search_tmp/13871818306523928435/pref tmpFolder/6144580022869075475/search_tmp/13871818306523928435/aln --tmscore-threshold 0 --lddt-threshold 0 --sort-by-structure-bits 1 --sub-mat 'aa:3di.out,nucl:3di.out' -a 0 --alignment-mode 3 --alignment-output-mode 0 --wrapped-scoring 0 -e 10 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 0.5 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:10,nucl:10 --gap-extend aa:1,nucl:1 --zdrop 40 --threads 176 --compressed 0 -v 3 

[=================================================================] 100.00% 1 eta -
Time for merging to aln: 0h 0m 0s 259ms
Time for processing: 0h 0m 23s 867ms
mvdb tmpFolder/6144580022869075475/search_tmp/13871818306523928435/aln tmpFolder/6144580022869075475/result -v 3 

Time for processing: 0h 0m 0s 225ms
Removing temporary files
rmdb tmpFolder/6144580022869075475/search_tmp/13871818306523928435/pref -v 3 

Time for processing: 0h 0m 0s 3ms
aln.m8 exists and will be overwritten
convertalis tmpFolder/6144580022869075475/query /home/liuhongbin/database/FoldSeek/pdb100/pdb tmpFolder/6144580022869075475/result aln.m8 --sub-mat 'aa:3di.out,nucl:3di.out' --format-mode 0 --format-output query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits --translation-table 1 --gap-open aa:10,nucl:10 --gap-extend aa:1,nucl:1 --db-output 0 --db-load-mode 0 --search-type 0 --threads 176 --compressed 0 -v 3 

[=================================================================] 100.00% 1 eta -
Time for merging to aln.m8: 0h 0m 0s 5ms
Time for processing: 0h 0m 0s 142ms
rmdb tmpFolder/6144580022869075475/result -v 3 

Time for processing: 0h 0m 0s 121ms
rmdb tmpFolder/6144580022869075475/query -v 3 

Time for processing: 0h 0m 0s 4ms
rmdb tmpFolder/6144580022869075475/query_h -v 3 

Time for processing: 0h 0m 0s 2ms
rmdb tmpFolder/6144580022869075475/query_ca -v 3 

Time for processing: 0h 0m 0s 3ms
rmdb tmpFolder/6144580022869075475/query_ss -v 3 

Time for processing: 0h 0m 0s 4ms

**Comment by martin-steinegger** [comment]
This structure is just a single helix. Please see my answers here https://github.com/steineggerlab/foldseek/issues/105

**Comment by BinhongLiu** [comment]
Great! Thanks!
