### ISSUE TITLE
How cigar_string is generated in tmaln-06.out?

### ISSUE THREAD

**Issue by ManlioWu** [steineggerlab/foldseek#114]
Recently I have been studying your 'foldseek-analysis' code, and I noticed that there is cigar_string in tmaln-06.out, which should be generated by TMalign. However, when I use TMalign, I cannot find this term. So I'm confused about it.

**Comment by martin-steinegger** [comment]
We used the CIGAR string (Compact Idiosyncratic Gapped Alignment Report) to represent the alignment. It encodes the alignment with operations (e.g., 'M' for match, 'I' for insertion, 'D' for deletion) and the associated number represents the number of consecutive occurrences of that operation.

**Comment by ManlioWu** [comment]
It means that CIGAR string is generated by yourself, not by TMalign. Right?

**Comment by ManlioWu** [comment]
> We used the CIGAR string (Compact Idiosyncratic Gapped Alignment Report) to represent the alignment. It encodes the alignment with operations (e.g., 'M' for match, 'I' for insertion, 'D' for deletion) and the associated number represents the number of consecutive occurrences of that operation.

It means that CIGAR string is generated by yourself, not by TMalign. Right? If so, can you provide the code? I cannot find it in your repo: foldseek-analysis
