### ISSUE TITLE
How cigar string is generated

### ISSUE THREAD

**Issue by ManlioWu** [steineggerlab/foldseek#115]
Hello, authors! In foldseek, you used pairs with tmscore>0.6 to train your model. I want to know how to get the cigar string of the pair alignment, and I cannot get it using TMalign. So could you tell me how you do or the parameter for TMalign to get the cigar string? Looking forward to your reply!

**Comment by martin-steinegger** [comment]
It is answered here https://github.com/steineggerlab/foldseek/issues/114

**Comment by ManlioWu** [comment]
> It is answered here #114

Sorry for missing this issue. Thanks!
