### ISSUE TITLE
repeated hits?

### ISSUE THREAD

**Issue by BinhongLiu** [steineggerlab/foldseek#120]
## Expected Behavior
search similar structures of PDB:6VE9 against the pdb100 database.
`foldseek easy-search pdbs/6ve9.pdb /home/liuhongbin/database/FoldSeek/pdb100/pdb aln1.m8 tmpFolder`
## Current Behavior
repeated hits with different `evalue` and `bits`

![image](https://user-images.githubusercontent.com/35453307/234570161-549ff66c-4a0c-4ca7-8e17-76e02a956ef4.png)

How to understand these "same" hits?

**Comment by martin-steinegger** [comment]
You are using an NMR structure, which contains many models. Each model was aligned against the same 6VE9_A structure in the PDB100.
