### ISSUE TITLE
Why is `easy-cluster` so much faster than `search` + `clust`

### ISSUE THREAD

**Issue by zdk123** [steineggerlab/foldseek#121]
## Expected Behavior

I expect cluster to be faster since it is using a pre-built database rather than pdb files.

## Steps to Reproduce (for bugs)
For about 17k structures, this command takes a few minutes:
```sh
foldseek easy-cluster -c 0.8  merged_pdbs/* ezclu80 tmpFolder
```
while this takes a ~hours
```sh
mkdir mergedDB
foldseek createdb merged_pdbs/* mergedDB/hits
foldseek search -c 0.8 mergedDB/hits mergedDB/hits aln80 tmpFolder 
foldseek clust mergedDB/hits aln80 clu80
foldseek createtsv mergedDB/hits mergedDB/hits clu80 clu80.tsv
```

Apologies, if I'm abusing `easy-cluster` or if I'm misunderstanding what's going on under the hood with it.

**Comment by martin-steinegger** [comment]
Please check out our manuscript about the [clustering](https://www.biorxiv.org/content/10.1101/2023.03.09.531927v1). We implemented multiple speedups like [Linclust](https://www.nature.com/articles/s41467-018-04964-5) and [cascaded clustering](https://academic.oup.com/bioinformatics/article/32/9/1323/1744460) to avoid the N^2 comparison problem that results from sequence/structure-based clustering algorithm.

**Comment by zdk123** [comment]
Thanks for the quick response. So I understood `foldseek clust` to be the clustering method described in the manuscript, but I see that the all-vs-all alignment is actually doing the heavy lifting here and is also being sped up in easy-cluster.

**Comment by zdk123** [comment]
One follow up - is there any plan to implement easy-cluster on a pre-build database?
This command dies:
```sh
foldseek easy-cluster -c 0.8  mergedDB/hits ezclu80 tmpFolder
```

**Comment by martin-steinegger** [comment]
The manuscript discusses the `foldseek cluster` method. 
`foldseek clust` performs clustering based on pre-computed similarities, `foldseek cluster` the process by executing both steps in an optimized manner.

I am not sure what you mean by pre-built database but you can use `cluster` with an foldseek database.
```
foldseek cluster inputDB clusterDB tmp -c 0.8
foldseek createtsv inputDB inputDB clusterDB clusterDB.tsv
```

**Comment by zdk123** [comment]
`foldseek cluster` is the command I was missing! And it's right there in `foldseek -h` page too 🤕 . thank you!
