### ISSUE TITLE
Generate alignments/give rotation&translation matrix

### ISSUE THREAD

**Issue by gezmi** [steineggerlab/foldseek#13]
Hi,

It is a very nice software and extremely fast, thank you! One question: would it be possible that the server provides the superimposed structures and/or the translation-rotation matrix for the query vs hits? That would be super useful!

Thank you for your great work!

**Comment by martin-steinegger** [comment]
Thank you! This is quite high on our todo list but it still might need a bit of time to be built.

**Comment by phiweger** [comment]
Hi, are these alignments already available using the command line tool @martin-steinegger , eg to visualise/ superimpose the 3D models of a pair of proteins?

**Comment by phiweger** [comment]
@martin-steinegger I get 12 coords in one line; I have not been able to figure out which 3 correspond to translation and which 9 to rotation. 

I want to feed this info to rotate the structures "manually" using 

https://biopython.org/docs/1.75/api/Bio.PDB.Atom.html#Bio.PDB.Atom.Atom.transform

which takes a 3x3 rotation matrix, however, I am not sure about which value in `aln_tmscore.tsv` goes where (the array indices).

Thanks for the patient help!

**Comment by phiweger** [comment]
If anyone stumbles upon this: The first 3 entries are translation, the remaining one rotation, so this

`query ref 4.711E-01 59.289 21.504 63.313 -0.707 -0.706 0.041 -0.695 0.704 0.151 -0.135 0.078 -0.988`

becomes this:

```python
import numpy as np

rotation = np.array([[-0.707, -0.706, 0.041], [-0.695, 0.704, 0.151], [-0.135, 0.078, -0.988]])
translation = np.array([59.289, 21.504, 63.313])
```

**Comment by mrauha** [comment]
Is it possible to get these using API? 

The json contains tCa for each alignment, list of floats with 3*n_res elements. Plotted a few, turns out they're not the aligned CAs: 

![Screenshot 2022-06-02 at 14 51 31](https://user-images.githubusercontent.com/20420759/171623264-7def13f2-3b50-40c1-b013-5963defa36ba.png)

**Comment by mrauha** [comment]
I see. Not a big problem, I can download the structures and do it locally. Thanks for the quick reply & awesome work!

**Comment by martin-steinegger** [comment]
@gezmi we added a structural viewer to the foldseek server. You can also get a static HTML using the binary using `--format-mode 3`

**Comment by jmrussell** [comment]
Should the output html from --format-mode 3 include a visualization of the overlaid alignment like the web server does?

**Comment by milot-mirdita** [comment]
It should, does it not work for you? Can you try a different browser?

**Comment by jmrussell** [comment]
Thanks for the quick response! It wasn't a browser issue, but your suggestion made me realize it likely due to the way I was serving the html from a webserver; downloading the html and opening it directly worked in all browsers. Awesome software btw! Thanks
