### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Ch-rode** [steineggerlab/foldseek#130]
Hello ! I was trying to install foldseek and I had an empty get.
![image](https://github.com/steineggerlab/foldseek/assets/61243245/739638b8-2889-46b3-8956-83badd40b3fd)
I think something is missing in the first 2 tar in the [download page](https://mmseqs.com/foldseek/)
Thanks

**Comment by milot-mirdita** [comment]
The disks of the server that hosts the binaries were full. I migrated to a different one. The binaries should be available again once this run has finished in about half an hour. Sorry!

https://github.com/steineggerlab/foldseek/actions/runs/4956626525

**Comment by milot-mirdita** [comment]
I mean this link:
https://github.com/steineggerlab/foldseek/runs/13428024888

**Comment by Ch-rode** [comment]
thanks a lot for the for the quick reply. no problem, i will  check it later :)

**Comment by milot-mirdita** [comment]
I set it to the last release that was still working. The latest precompiled binaries will require a bit more work to get back running.

**Comment by milot-mirdita** [comment]
I realize that I never updated this issue. This is fixed since a while. I migrated the download server to a different one.
