### ISSUE TITLE
Problems with PDB100 database

### ISSUE THREAD

**Issue by snayfach** [steineggerlab/foldseek#132]
## Current Behavior

- can't download PDB100 database
- can download PDB database, but using it with `easy-search` throws an error

## Steps to Reproduce (for bugs)

Can't download PDB100:
`foldseek databases PDB100 pdb100 tmp`
>Selected database PDB100 was not found

Can download PDB:
`foldseek databases PDB pdb tmp`
>Selected database PDB100 was not found

Can't use PDB with easy-search:
`foldseek easy-search data/structures pdb result.tsv tmp`
>Input database "pdb" has the wrong type (Aminoacid)
>Allowed input:
>- Flatfile
>- Directory

easy-search works using Swiss-Prot:
`foldseek databases Alphafold/Swiss-Prot swissprot tmp`
`foldseek easy-search data/structures swissprot result.tsv tmp`

## Your Environment
I'm using foldseek Version: 6.29e2557 installed with conda

**Comment by milot-mirdita** [comment]
I reuploaded the PDB. The download should work again (with `PDB`, not `pdb100`).

We have rebuilt the database to support clustered searches and i introduced an incompatibility. The downloader does not yet support the new format. But its backwards compatible now.

**Comment by snayfach** [comment]
Works now. Thanks.
