### ISSUE TITLE
Problem about K-mer 

### ISSUE THREAD

**Issue by yang-nei** [steineggerlab/foldseek#134]
<img width="1187" alt="截圖 2023-05-18 下午5 46 37" src="https://github.com/steineggerlab/foldseek/assets/122717414/24b2a3ac-6aac-4418-a9c2-2c003777d58d">
Hi there! I try to blast structure to databases being set by myself , However I faced some problem about "No k-mer could be extracted " and I'm sure my sequences length is more than 14 residues. How shell I do?

**Comment by milot-mirdita** [comment]
There is something wrong with your pdb tgz files. Foldseek does not find any structures insides. See the ignored 0 out of 0 line.

**Comment by martin-steinegger** [comment]
To search multiple PDBs try this: 
```
foldseek easy-search queryPdbFolder/ pdb_db aln tmp 
```
