### ISSUE TITLE
Exporting RMSD from Foldseek webserver.

### ISSUE THREAD

**Issue by FabrizioG202** [steineggerlab/foldseek#135]
Is it possible to obtain a column containing the RMSD for the alignment when downloading the m8 file from the foldseek webserver?

I noticed the RMSD in the alignment view within the result page but it does not appear to be saved as a column in the m8 file. I tried reverse-engineering the RMSD retrieval in the associated pull-request (#66) but if I understood correctly its just obtained from the parsed TM-Align result that I cannot access after I export the file.

**Comment by milot-mirdita** [comment]
The webserver RMSDs are computed on the fly with a webassembly based TM-align. So they are not actually available in the m8. You can output RMSDs in the command line version though with the `--format-output rmsd` parameter.
