### ISSUE TITLE
Fasta sequence search using command line version

### ISSUE THREAD

**Issue by AntonS-bio** [steineggerlab/foldseek#138]
The webserver version has a very useful feature that, as I understand it:
1) searches for closest match of protein amino sequences (fasta) in AFDB and other datasets
2) uses the AFDB predicted structure (pdb) of the best match identified in (1) to search for best matching structure

I didn't find this functionality in the command line version. To avoid reinventing the wheel, could you please share the code behind step (1)?

Thank you.

**Comment by milot-mirdita** [comment]
Do you mean the predict structure button? That one works by calling the ESMFold API (https://esmatlas.com/about#api) to predict structures of short sequences (up to 400 AA). You can call the API with curl/wget and then call Foldseek afterwards.

**Comment by AntonS-bio** [comment]
Thanks a lot!
