### ISSUE TITLE
Error running example 

### ISSUE THREAD

**Issue by git198** [steineggerlab/foldseek#14]
## Expected Behavior
Run example without error
```
foldseek createdb example/ targetDB
foldseek createdb example/ queryDB
foldseek search queryDB targetDB aln tmpFolder -a
foldseek aln2tmscore queryDB targetDB aln aln_tmscore
foldseek createtsv queryDB targetDB aln_tmscore aln_tmscore.tsv
```

## Current Behavior
Input database is not compatible with aln2tmscore.

```
aln2tmscore queryDB targetDB aln aln_tmscore 

MMseqs Version: 188e5299e4d4e47b94614c4e8c67032f78f3ed21
Threads         96
Compressed      0
Verbosity       3

Input database "queryDB" has the wrong type (Aminoacid)
Allowed input:
- Unknown
```

## Steps to Reproduce (for bugs)
Here is bash script that downloads: foldseek binary and  git repo ,to get the example data, and runs the provided example generating the error.
```
#Create working directory
WORK_DIR=./foldseek_linux_avx

if [ -d $WORK_DIR ]; then
     rm -rf $WORK_DIR
fi
mkdir $WORK_DIR
cd $WORK_DIR

#Download binary
wget https://mmseqs.com/foldseek/foldseek-linux-avx2.tar.gz --no-check-certificate
tar xvzf foldseek-linux-avx2.tar.gz
foldseek_bin=./foldseek/bin/foldseek

#Get test data
git clone https://github.com/steineggerlab/foldseek.git ./foldseek_git_src
EXAMPLE_DATA=./foldseek_git_src/example/


#Run foldseek; Generate error
$foldseek_bin createdb $EXAMPLE_DATA targetDB
$foldseek_bin createdb $EXAMPLE_DATA queryDB
$foldseek_bin search queryDB targetDB aln tmpFolder -a
$foldseek_bin aln2tmscore queryDB targetDB aln aln_tmscore
$foldseek_bin createtsv queryDB targetDB aln_tmscore aln_tmscore.tsv

```

## Context
I've also run the example with all 3 available compiled version (avx, sse and conda) and got the same error "Input database "queryDB" has the wrong type".
It will be nice to have a function that can check if an input database is compatible with a function or another. 

Thank you

**Comment by martin-steinegger** [comment]
Thank you for reporting this. It should be fixed now. It was a wrong `dbtype` check.

**Comment by phiweger** [comment]
@martin-steinegger the conda recipe is still affected from this

**Comment by martin-steinegger** [comment]
yes, we did not update conda yet. But our statically compiled version should contain the fix.

**Comment by phiweger** [comment]
yes, that one works :)
