### ISSUE TITLE
Cann't download pdb databases

### ISSUE THREAD

**Issue by hongzhonglu** [steineggerlab/foldseek#140]
Hello @martin-steinegger , I just run the command line on my linux computer:  
foldseek databases PDB pdb tmp
foldseek databases Alphafold/UniProt50 afdb tmp
However, the target file can not be downloaded.
Can you help to find the reason? Thanks very much!

Best,
Hongzhong

**Comment by milot-mirdita** [comment]
We are using Cloudflare R2 to host the database, which seems to have an issue when used in China (see https://github.com/steineggerlab/foldseek/issues/110#issuecomment-1513636499). I don't really have a good workaround currently, except to try to use a VPN.
