### ISSUE TITLE
Diference between alntmscore and TM-score calculated by US-align

### ISSUE THREAD

**Issue by hongzhonglu** [steineggerlab/foldseek#147]
Dear Prof. Martin Steinegger @martin-steinegger,
I just check the result from foldseek easy-search mode and find that a lot of target protein with alntmscore smaller than 0.5 but the related homolog probability is equal to 1.  As defined in US-align, if TM-score is smaller than 0.5, the two structures are different in the topology structure. So it is not clear to see how 'alntmscore' given by foldseek reflect the structure similarities. Can you give me some comments about this? Thanks a lot!

Best,
Hongzhong

**Comment by martin-steinegger** [comment]
A TM-score of less than 0.3 typically indicates a random alignment, while a TM-score between 0.3 and 0.5 suggests that the alignment could be random or from the same fold. A TM-score greater than 0.5 indicates that the alignment is likely from the same fold. However, it's important to be cautious when dealing with the normalization of the TM-score. In this case of `alntmscore` we normalize the TM-score over the length of the alignment, which differs from `qtmscore` that is normalized by the length of the query structure. `alntmscore` could be > 0.5 for very short fragments, e.g. just a single helix. So, it is very important to handle normalization carefully, depending on your use-case. Another issue that might arise is that TM-score requires two well-superposable structures, which in the case of multi-domain AlphaFold predictions might only sometimes be the case. 
Our `e-value` and `prob` should not suffer from either of these problems. Therefore, I would consider relying on the `e-value` and `prob` values to assess the similarity.
