### ISSUE TITLE
Filter DB by taxnomy

### ISSUE THREAD

**Issue by adimil** [steineggerlab/foldseek#148]
Hi Milot and Martin,

I have downloaded the Alphafold/UniProt50 DB using the `foldseek databases` command.
I would like remove all Eukaryotic proteins from this DB, what would be the easiest way?

I tried `filtertaxdb`:
`foldseek filtertaxdb UniProt50 UniProt50_taxonomy filteredTaxDB --taxon-list '!2759'
`
But getting the following error:
```
filtertaxdb UniProt50 UniProt50_taxonomy filteredTaxDB --taxon-list !2759

MMseqs Version: 53465f07cdeed1f7fda08ee7f188327cb57c37ba
Compressed      0
Selected taxa   !2759
Threads         80
Verbosity       3

Input database "UniProt50_taxonomy" has the wrong type (Generic)
Allowed input:
- Taxonomy
```

Thanks,
Adi

**Comment by milot-mirdita** [comment]
`filtertaxseqdb` is the command you want.

However you have to also subset the other Foldseek databases. The following should work:
```
foldseek filtertaxseqdb UniProt50 UniProt50_subset --taxon-list "!2759"
rm UniProt50_subset_h*
mmseqs createsubdb UniProt50_subset.index UniProt50_h UniProt50_subset_h
mmseqs createsubdb UniProt50_subset.index UniProt50_ss UniProt50_subset_ss
mmseqs createsubdb UniProt50_subset.index UniProt50_ca UniProt50_subset_ca
```

**Comment by adimil** [comment]
Yes, prefect. Thank you!
