### ISSUE TITLE
foldseek search plddt filter

### ISSUE THREAD

**Issue by Fede112** [steineggerlab/foldseek#150]
Hi Milot and Martin,
I have a question regarding my current usage of Foldseek for clustering a specific subset of the Alphafold database to identify domains.

I have been exploring the foldseek search results, and I was wondering if there is a way to apply a filter based on the average plddt of either the query or target. Specifically, I would like to narrow down the results based on this criterion.

I am aware that there is an option to mask residues during the database creation process (--mask-bfactor-threshold), but since I am working with prebuilt databases, this may not be applicable in my case. 

I would appreciate any guidance or suggestions you might have on implementing such a filter. 

Thank you in advance.
Federico

**Comment by milot-mirdita** [comment]
We don't keep the pLDDT values after creating a foldseek database. Our compressed foldcomp AFDB database contains discretized pLDDT values, but doesn't have any easy filtering options yet.

What we did internally to do any pLDDT analyses is to download accession to pLDDT metrics directly from the Google Cloud Big Query interface, it went something like the following:

```
EXPORT DATA OPTIONS( uri='gs://foldseek_lddt_mapping/afdb_entry_plddt_mapping_*.csv', format='CSV', compression='GZIP', overwrite=true, header=true, field_delimiter=';') AS SELECT entryId, latestVersion, globalMetricValue FROM `bigquery-public-data.deepmind_alphafold.metadata` ORDER BY entryId ASC 

gsutil -m cp  gs://foldseek_lddt_mapping/afdb* tmp/
zcat afdb_entry_plddt_mapping_0000000000{00..32}.csv  > afdb_entry_plddt_mapping.csv
```

And then do subset of the database based on this file (with e.g. `awk` and `createsubdb`).

**Comment by Fede112** [comment]
Thanks for the quick reply!
I will attempt to download the pLDDTs using the Google Cloud Big Query interface.
Once again, thank you for sharing the snippet.
