### ISSUE TITLE
[Web service] "Error loading search result"

### ISSUE THREAD

**Issue by kaymccoy** [steineggerlab/foldseek#152]
## Expected Behavior

Search works

## Current Behavior

Search does not work; says "Error loading search".

## Steps to Reproduce (for bugs)

Upload PDB to https://search.foldseek.com/search, use 3Di / AA mode to search the PDB100 database, see that search does not run

## Foldseek Output (for bugs)

Says "Error loading search result", see screenshot below
<img width="941" alt="Screenshot 2023-06-28 at 12 56 25 PM" src="https://github.com/steineggerlab/foldseek/assets/20246007/60dedfee-b6f4-4839-96db-bdbd997312fe">

## Your Environment

Webserver, Chrome Version 114.0.5735.133 (Official Build) (x86_64)

**Comment by milot-mirdita** [comment]
Thanks for notifying us. The disk of the server was full. I freed some space, submitting jobs should work again.

**Comment by kaymccoy** [comment]
Thanks, it works great now!
