### ISSUE TITLE
Increasing cluster stringency?

### ISSUE THREAD

**Issue by richardshuai** [steineggerlab/foldseek#156]
I'm trying to cluster a dataset of thousands of highly similar protein structures using foldseek cluster, but I'm finding that foldseek gives me very few clusters (maybe 30-40) even with very strict structural alignment cutoffs (-c 0.999, -e 0.001). However, the structures within a given cluster do still look different when viewed in PyMOL. How would I go about further increasing cluster stringency these cutoffs?

**Comment by martin-steinegger** [comment]
Interesting, I never tried to cluster highly similar structures. 
Yes, you can combine cluster criteria. 
Increasing the coverage does make sense for your use-case.
