### ISSUE TITLE
Foldseek API returning "500 Internal Server Error"

### ISSUE THREAD

**Issue by DaRinker** [steineggerlab/foldseek#158]
## Expected Behavior
Successful API query using locally stored PDB file

## Current Behavior
API query returns "500 Internal Server Error"

## Steps to Reproduce (for bugs) 
[note: I added the "-v" to but the remainder of the command is as specified on the site]

curl -v -X POST -F q=@PATH_TO_MY.pdb -F 'mode=tmalign' -F 'database[]=afdb50' -F 'database[]=afdb-swissprot' -F 'database[]=afdb-proteome' -F 'database[]=cath50' -F 'database[]=mgnify_esm30' -F 'database[]=pdb100' -F 'database[]=gmgcl_id' https://search.foldseek.com/api/ticket

## Foldssek Output (for bugs)
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 147.46.145.3:443...
* Connected to search.foldseek.com (147.46.145.3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /accre/arch/easybuild/software/BinDist/Anaconda3/2022.05/ssl/cacert.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=search.foldseek.com
*  start date: May 11 05:17:07 2023 GMT
*  expire date: Aug  9 05:17:06 2023 GMT
*  subjectAltName: host "search.foldseek.com" matched cert's "search.foldseek.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: POST]
* h2h3 [:path: /api/ticket]
* h2h3 [:scheme: https]
* h2h3 [:authority: search.foldseek.com]
* h2h3 [user-agent: curl/7.82.0]
* h2h3 [accept: */*]
* h2h3 [content-length: 137867]
* h2h3 [content-type: multipart/form-data; boundary=------------------------567ae3d1cc2af231]
* Using Stream ID: 1 (easy handle 0x55c1fdcb5ae0)
> POST /api/ticket HTTP/2
> Host: search.foldseek.com
> user-agent: curl/7.82.0
> accept: */*
> content-length: 137867
> content-type: multipart/form-data; boundary=------------------------567ae3d1cc2af231
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* We are completely uploaded and fine
< HTTP/2 500 
< server: nginx
< date: Wed, 05 Jul 2023 19:03:25 GMT
< content-type: text/html
< content-length: 170
< 
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host search.foldseek.com left intact

**Comment by martin-steinegger** [comment]
It should work again. The disk was full.
