### ISSUE TITLE
aln2tmscore freezes

### ISSUE THREAD

**Issue by Pooryamb** [steineggerlab/foldseek#17]
Hi,

Thanks for your amazing program. I have noticed if the following structure is in my query database, after I search it against PDB, aln2tmscore freezes. 

The problem happens if this protein is in my list of queries: https://alphafold.ebi.ac.uk/entry/Q381H2
My foldseek version: 2dd3b2f427b9195506836764946853a89f2e7d44
I use a statistically compiled program(avx2). 

Best,

**Comment by martin-steinegger** [comment]
Could you please postexample data and commands to reproduce the problem?

**Comment by Pooryamb** [comment]
foldseek createdb input/ InpDB
foldseek search InpDB pdb aln tmpFolder -a
foldseek aln2tmscore InpDB pdb aln aln_tmscore
[input.zip](https://github.com/steineggerlab/foldseek/files/8849673/input.zip)

**Comment by martin-steinegger** [comment]
Thank you! It should be fixed now. The float SIMD Kabsch caused the issue, we fall back to the old Kabsch in cases when it does.
