### ISSUE TITLE
How to obtain a complete PDB through foldssek?

### ISSUE THREAD

**Issue by jiaweiguan** [steineggerlab/foldseek#172]
`foldseek easy-search ./query/ {database_path} tmp --format-mode 5`

Result: 
![image](https://github.com/steineggerlab/foldseek/assets/32994356/ae700036-b59a-4350-9ce2-c1666e911b10)

From the returned results, it can be seen that only Ca. Is there any other way for me to obtain a complete PDB?

**Comment by jiaweiguan** [comment]
Thank you for your help!

**Comment by jiaweiguan** [comment]
@martin-steinegger 
Hi, professor.
Is the following dataset clustered when creating foldseek databases? Can I first search for structures using `foldseek easy-search` and then use `foldseek easy-cluster` for sequence clustering? Obtain some sequence families through this method. For me, whether the protein database is pre clustered is an important information.

```
  Name                   	Type     	Taxonomy	Url
- Alphafold/UniProt   	Aminoacid	     yes	https://alphafold.ebi.ac.uk/
- Alphafold/UniProt50 	Aminoacid	     yes	https://alphafold.ebi.ac.uk/
- Alphafold/Proteome  	Aminoacid	     yes	https://alphafold.ebi.ac.uk/
- Alphafold/Swiss-Prot	Aminoacid	     yes	https://alphafold.ebi.ac.uk/
- ESMAtlas30          	Aminoacid	       -	https://esmatlas.com
- PDB                 	Aminoacid	     yes	https://www.rcsb.org
```

**Comment by martin-steinegger** [comment]
Neither of these databases is clustered by `foldseek easy-cluster`. We only provide databases clustered by structure. Like the Alphafold/UniProt50 and ESMAtlas30 were clustered through [MMSeqs2](https://github.com/soedinglab/mmseqs2).

However, we did cluster the whole Alphafold/UniPort as part of our [cluster work](https://www.biorxiv.org/content/10.1101/2023.03.09.531927v1). If you want to use these structurally clustered proteins you can download the representatives through [foldcomp](https://github.com/steineggerlab/foldcomp), the db is called `afdb_rep_v4`.

**Comment by jiaweiguan** [comment]
`We only provide databases clustered by structure.` 
Does it mean that structural clustering is performed before creating the database?

**Comment by martin-steinegger** [comment]
Sorry for the confusion. I meant "We only provide databases clustered by amino acid sequence.". E.g. the UniProt50 is clustered using MMseqs2 `mmseqs cluster afdb afdb50 tmp --min-seq-id 0.5 -c 0.9 --cluster-reassign 1`

**Comment by jiaweiguan** [comment]
Got it! Thanks!

**Comment by jiaweiguan** [comment]
`foldseek easy-search ./1QYS.pdb ./afdb/afdb res.8m tmp --format-mode 4`
When I execute the this command, I found some warnings in the log.
`Can not touch 415722228266 into main memory`

But I still got the search results. I don't know if this result is complete, can this warning be ignored?

**Comment by jiaweiguan** [comment]
@martin-steinegger 
`foldseek easy-search ./1QYS.pdb ./afdb/afdb res.8m tmp --format-mode 4`
When I execute the this command, I found some warnings in the log.
`Can not touch 415722228266 into main memory`

But I still got the search results. I don't know if this result is complete, can this warning be ignored?

**Comment by jiaweiguan** [comment]
Is ‘tstart’ starting from 0 or 1?
