### ISSUE TITLE
compatible conda environment?

### ISSUE THREAD

**Issue by twaksman001** [steineggerlab/foldseek#175]
unable to conda install foldseek because of conflicts with other packages.

can you provide a file specifying a compatible conda environment?

**Comment by milot-mirdita** [comment]
Does the error also happen if you create a fresh conda environment?

**Comment by twaksman001** [comment]
installing into base environment worked ok, so the issue must have been due to installation of other packages into the environment before foldseek

**Comment by milot-mirdita** [comment]
Great! I would recommend to create many small and project-specific environments instead of few larger ones. I'll close the issue.
