### ISSUE TITLE
The search results do not match the condition

### ISSUE THREAD

**Issue by jiaweiguan** [steineggerlab/foldseek#180]
search statement：
`foldseek easy-search {fold_path}/query {database_path} {save} {fold_path}/tmp_{database}
                    --alignment-type 2 --format-mode 4 --format-output query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,alntmscore,bits,qseq,tseq,qaln,taln,cigar,qcov,tcov
                     -c 0.8 --cov-mode 2`

part result：
{"query": "1IWY.pdb", "target": "AF-A0A401Q9N3-F1-model_v4", "fident": 0.463, "alnlen": 41, "mismatch": 22, "gapopen": 0, "qstart": 84, "qend": 124, "tstart": 76, "tend": 116, "evalue": 0.08076, "alntmscore": 0.8709, "bits": 87, "qseq": "KVFERCELARTLKRLGMDGYRGISLANWMCLAKWESGYNTRATNYNAGDRSTDYGIFQINSRYWCNDGKTPGAVNACHLSCSALLQDNIADAVACAKRVVRDPQGIRAWVAWRNRCQNRDVRQYVQGCGV", "tseq": "MAENESVGKIQKQFQVVTCALFRCCATQLQKYKAVAPDRLRFKLEESTSQRNRGLLSLILVTFPVPHRFFQHPFDFLNSDIINDILCAKRVVRDSQGMGAWYGWKDNCRNRDLSHFLD", "qaln": "LLQDNIADAVACAKRVVRDPQGIRAWVAWRNRCQNRDVRQY", "taln": "FLNSDIINDILCAKRVVRDSQGMGAWYGWKDNCRNRDLSHF", "cigar": "41M", "qcov": 0.315, "tcov": 0.347}

Hi, @martin-steinegger 
I have set the cov-mode to “2”(coverage of query) and c is greater than 0.8. But the search results still have qcov=0.315. What is the reason？

**Comment by martin-steinegger** [comment]
Oh, this bug was introduced when we changed the alignment algorithm. This is fixed now. 
Thank you so much for reporting this. This is a bad bug.
