### ISSUE TITLE
download the raw pdb files of PDB100 database

### ISSUE THREAD

**Issue by BinhongLiu** [steineggerlab/foldseek#184]
## Expected Behavior
I want to validate the structural similarity of the top N hits reported by `foldseek easy-search example.pdb PDB100 aln.m8 tmpFolder` with other different tools.
Is there any way to download the raw pdb files of PDB100 database, so that I can validate the structural similarity between  example.pdb and the top N hits using other tools or manually?

Thanks!

**Comment by milot-mirdita** [comment]
You can download the PDB directly from the RCSB and their mirrors:
https://www.rcsb.org/docs/programmatic-access/file-download-services
