### ISSUE TITLE
`structureto3didescriptor` yield wrong sequence output when it meets alternative residue conformation and amino acid ligands

### ISSUE THREAD

**Issue by NatureGeorge** [steineggerlab/foldseek#189]
## Expected Behavior

`foldseek structureto3didescriptor` reads a PDB file, extract the protein sequence, then output corresponding 3Di sequence.

## Current Behavior

`foldseek structureto3didescriptor` output *a slightly incorrect result* when it reads PDB file containing residues with alternative conformation/location or ligands that are amino acids. To be clear, 

___incorrect output sequence -> unnecessary additional/alternative residues in protein sequences and 3Di sequences.___

## Steps to Reproduce 

```bash
foldseek structureto3didescriptor 3JQH.cif.gz 3JQH_output.tsv
```

or PDB 1EJG etc.

## Foldssek Output (for bugs)

* True protein sequence: PEKSKLQEIYQELTRLKAAVGEL (length 23)
* current foldseek output protein sequene: P**S**EKSKLQEIYQELTR**QE**LKAAVGEL (length 23+**3**=26)
* current foldseek output 3Di sequene: DDDPVVVVVVVVVVCLVVVVVVVVVD (length 26)

## Context

Quick fix: use gemmi's `first_conformer` function to remove alternative residue conformation:

https://github.com/steineggerlab/foldseek/blob/1f13fa7bb9848356c49ee6cefb77946a000a2d8e/lib/gemmi/model.hpp#L273-L277

As well as gemmi's `get_polymer` function to remove ligands:

https://github.com/steineggerlab/foldseek/blob/920bbf26ac9c52696f46974a9fd9ff833011cf12/lib/gemmi/model.hpp#L486-L498

## Your Environment

foldseek Version: 8.ef4e960

**Comment by milot-mirdita** [comment]
Would you be willing to make a pull request? I can merge it afterwards and you get credit in GitHub/next release notes.

**Comment by NatureGeorge** [comment]
Since I cannot compile from source under my PC environment (encounter `undefined reference to symbol 'dlsym@@GLIBC_2.2.5'` during `make`), I am not sure whether my following modification fix this issue:

My modification is:

Change from

https://github.com/steineggerlab/foldseek/blob/a435618b95ba95cbfe74dcbc8b4bd2720547d285/lib/foldcomp/src/structure_reader.cpp#L48

to

```python
for (gemmi::Residue& res : ch.get_polymer().first_conformer()) { 
```

If you have time to test this and it works well, I will make a PR for this change.  Otherwise, the actual place to be fixed would require someone to investigate.
