### ISSUE TITLE
Unrecognized parameter "--dbtype" when running easy-cluster

### ISSUE THREAD

**Issue by laelbarlow** [steineggerlab/foldseek#2]
## Expected Behavior
Cluster structures in a given database made using foldseek createdb.

## Current Behavior
When running easy-cluster on a very small set of 10 PDB structures, running the following command
```
foldseek easy-cluster ./target_db ./output_cluster ./tmp
```
results in this error message:
```
usage: foldseek createdb <i:PDB|mmCIF[.gz]> ... <i:PDB|mmCIF[.gz]> <o:sequenceDB> [options]
 By Martin Steinegger <martin.steinegger@snu.ac.kr>
options: common:
 --threads INT   Number of CPU-cores used (all by default) [4]
 -v INT          Verbosity level: 0: quiet, 1: +errors, 2: +warnings, 3: +info [3]

examples:
 Convert PDB/mmCIF files to an db.

references:
 - Steinegger M, Soding J: MMseqs2 enables sensitive protein sequence searching for the analysis of massive data sets. Nature Biotechnology, 35(11), 1026-1028 (2017)
Unrecognized parameter "--dbtype". Did you mean "--threads" (Threads)?
```

Looks like perhaps foldseek easy-cluster is trying to run foldseek createdb with an outdated option.

## Environment
I used the precompiled binary for osx from https://mmseqs.com/foldseek/

foldseek-osx-universal.tar.gz                      09-Jul-2021 07:55             6998109

foldseek Version: 75bb2e3a2718903f47008d7d8cc3be099e35d1e9

Operating system version: macOS Catalina 10.15.7

**Comment by martin-steinegger** [comment]
Clustering is currently not implemented. Only the following commands should work 

`easy-search`, `createdb`, `align`, `aln2tmscore`. 

Foldseek is still under development.
