### ISSUE TITLE
Web Service Fails/Hangs when Using TM-align mode

### ISSUE THREAD

**Issue by kthurimella** [steineggerlab/foldseek#21]
When searching any protein on the web server (https://search.foldseek.com/) I continue to get failures when using the TM-align mode. I tried this with a number of proteins and loaded accessions.

**Comment by kthurimella** [comment]
Here is the URL: https://search.foldseek.com/queue/d-4_TYSVkb6hW0uS0kNPzTtEYEM-Iz7BzN0T_w

I've attached screenshots for the AF accession: O43692
![Screen Shot 2022-07-01 at 7 05 35 PM](https://user-images.githubusercontent.com/2440047/176947778-2448e9f3-6095-409b-abdb-a354ef7e3bef.png)
![Screen Shot 2022-07-01 at 6 03 06 PM](https://user-images.githubusercontent.com/2440047/176947782-d0f596bd-5666-4b94-b6bd-bb268f979da3.png)
![Screen Shot 2022-07-01 at 5 52 30 PM](https://user-images.githubusercontent.com/2440047/176947783-86879cce-4218-4fb6-bf73-bc4d6849de9a.png)

**Comment by milot-mirdita** [comment]
I think your request hit a time limit and was cancelled. TMalign is despite our optimizations still quite slow. I would recommend to submit the structure with less databases selected when using the TM-align mode.
