### ISSUE TITLE
What lndb is doing ?

### ISSUE THREAD

**Issue by DomML** [steineggerlab/foldseek#210]
I saw the foldseek lndb used here and there, but I don't find information about it's function ?
Best regards,
Dominique MIAS-LUCQUIN.

**Comment by milot-mirdita** [comment]
It creates [symlinks](https://en.wikipedia.org/wiki/Symbolic_link) for all of the individual database files.
Especially with split datafiles (`.0`, `.1`, ..., `.n`) it would be very uncomfortable to call `ln -s` on all of them.

There are also similar commands for `mv`, `cp` and `rm` for the same purpose.

**Comment by DomML** [comment]
Thank you!
Best,
DML.
