### ISSUE TITLE
Questions on effects and usage of --num-iterations options

### ISSUE THREAD

**Issue by yakomaxa** [steineggerlab/foldseek#215]
We found that foldseek has option `--num-iterations` in a release note: https://github.com/steineggerlab/foldseek/releases/tag/4-645b789. 

I'm interested in this but found no documentations on this. 

What effect does this option have? I guess this is probably based on profile search and related to 3Di-based searches, but is this correct guess? Is this also applicable to searches based on TM-align?

Best regards

**Comment by milot-mirdita** [comment]
It does a PSI blast like search, from the initial sequence/structure to sequence/structure search, it generates a PSSM for each query then does profile to sequence/structure searches in multiple iterations.

We haven't extensively benchmarked this yet. We will do this at some point for some upcoming publication. But it should increase search sensitivity further.

**Comment by yakomaxa** [comment]
Thank you for clarification! I tried the option and it seems working correctly. I'm looking forward to seeing your publication on this.
