### ISSUE TITLE
How is the PDB100 database prepared?

### ISSUE THREAD

**Issue by BinhongLiu** [steineggerlab/foldseek#217]
If I didn't get it wrong, the PDB100 database was built based on 100% sequence identity clustered PDB. I checked the `pdb.lookup` file, which supposedly contains all the pdb_chain IDs, and found some strange chain IDs were included, like `1a0n_MODEL_1_B` , `1a0n_MODEL_2_B` and `1a0n_MODEL_3_B`. I could not find the corresponding chain that named this from the `1a0n` from PDB. And what is the difference between these `1a0n_MODEL_*_B` chains?

I'll be much appreciate if you could help me with this problem. Many thanks.

**Comment by milot-mirdita** [comment]
The script to create the PDB100 is here:
https://github.com/steineggerlab/foldseek/blob/master/util/update_webserver_pdb/single-script.sh
Not sure what the weird chains are, I have to look closer into it, these might be weird NMR structures that we don't handle correctly.
