### ISSUE TITLE
[Web service] "Error loading search result"

### ISSUE THREAD

**Issue by 10myl200** [steineggerlab/foldseek#22]
![Capture](https://user-images.githubusercontent.com/20413024/179616962-03949737-8d3e-404a-91fd-e77a0f4efd38.PNG)
Hi, I got this error from the Foldseek webserver. I tried both modes, and there was no difference. Could you check this problem?

**Comment by martin-steinegger** [comment]
It is working again. The issue was a full hard disk. 
Sorry for the inconvenience.

**Comment by romansloutsky** [comment]
Hi! I found this comment threat by searching for "Error loading search result" -- I am experiencing this issue right now. Is the same hard disk issue causing this again? Thank you!

<img width="601" alt="2023-07-05_17-28-28" src="https://github.com/steineggerlab/foldseek/assets/4968406/f801db18-0a16-49a8-9bd2-dc47445cb7a5">

**Comment by milot-mirdita** [comment]
Everything should work again, thank you for letting us know!
