### ISSUE TITLE
Back Translate 3Di Tokesn to PDB Format

### ISSUE THREAD

**Issue by mahdip72** [steineggerlab/foldseek#225]
Hello, I have a few questions which might be very basic to others.

1. Can we convert the 3Di tokens produced by foldseek into the actual 3D structure format like PDB files?

2. How can I compare two sequences of predicted and true 3Di tokens? Can I use something like the TM Score for that? I am working on a model to predict 3Di tokens from amino acids and am searching for the best metric to evaluate the model.

I would be very greatful to whom can answer my questions.

**Comment by Leo-T-Zang** [comment]
#https://github.com/steineggerlab/foldseek/issues/273
