### ISSUE TITLE
How to do local search and report TM-scores

### ISSUE THREAD

**Issue by Pooryamb** [steineggerlab/foldseek#23]
Dear foldseek developers,

I want to search many structures against many structures using foldseek, and I want to do local structure searching. I need to know the TM-score and the coordinates of the part of the query that aligns with the target i.e. qstart, qend, tstart, and tend. 
As I need to do local alignment, I didn't use "--alignment-type 1" which is for the global alignment.
 
When I use the following code, it doesn't show qstart, qend, tstart, and tend. 

_foldseek createdb example/ targetDB
foldseek createdb example/ queryDB
foldseek search queryDB targetDB aln tmpFolder -a
foldseek aln2tmscore queryDB targetDB aln aln_tmscore
foldseek createtsv queryDB targetDB aln_tmscore aln_tmscore.tsv_

How can I do local alignment and also have the qstart, qend, tstart, and tend? 
I was thinking of running the search with default mode (that reports hit based on e-value) and then merging the data from this step with the table I get from converting alignments with e-value to tm-score. However, if a query protein has multiple domains that all align with the same template protein, it would fail.

**Comment by milot-mirdita** [comment]
`convertalis` has learned a few new output columns in the last release (`--format-output qca,tca,alntmscore,u,t`).
To produce the normal blast-tab output + TM-score you can call:

```
foldseek convertalis queryDB targetDB aln aln.m8 --format-output "query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,alntmscore"
```

**Comment by Pooryamb** [comment]
Thanks for the quick reply!
