### ISSUE TITLE
CATH domains in local foldseek

### ISSUE THREAD

**Issue by dadush1** [steineggerlab/foldseek#232]
I see that the webserver also returns hits for CATH domains. I don't see the CATH databases in the `databases`, but I did see in an earlier issue something about the possibility of it.
Is it possible somehow to run it locally against CATH domains?

**Comment by martin-steinegger** [comment]
We added the database. In the newest version of foldseek you should be able to download it like this: 
```
foldseek databases CATH50 cath50 tmp
```

**Comment by dadush1** [comment]
great! thank you very much!
