### ISSUE TITLE
Searching against all the databases and specific organism

### ISSUE THREAD

**Issue by ahof1704** [steineggerlab/foldseek#251]
Hi,

Fantastic work! I have two questions: 
1) Can I pass a list of databases I would like to search over? All the examples I have seen so far specify a single database, but I would like to search all the available databases, similar to what is done on the web application. 

2) Can I specify the organism? I have a particular interest in human homologs. 

Thanks!

**Comment by milot-mirdita** [comment]
1) No, you have to repeatedly call search/easy-search on each database.
2) `--taxon-list 9606` is the parameter you are looking for.

**Comment by ahof1704** [comment]
Thank you!
