### ISSUE TITLE
pre-trained 3Di embedding

### ISSUE THREAD

**Issue by chooyu1998** [steineggerlab/foldseek#252]
I understand that the VQ-VAE used by foldseek translates each amino acid into one of 20 state. (before: VAL amino acid after: ALA amino acid) so is there a way to get pre-trained 3Di embedding before translating the 20 states?

**Comment by milot-mirdita** [comment]
A community member has ported the VQ-VAE to numpy:
https://github.com/althonos/mini3di

This should be the easiest way to play with the individual NN layers.

You might also want to consider ProstT5 for structural embeddings. Generating 3Di from ProstT5 works very well.

**Comment by chooyu1998** [comment]
Thanks for your quick response!
