### ISSUE TITLE
3di for multi-chain protein

### ISSUE THREAD

**Issue by Zhu-Siqi** [steineggerlab/foldseek#262]
Hi, I want to transform my multi-chain protein to 3di token sequence. When encoding the protein, I wonder whether the 3di tokens are encoded based on the atom coordinates of all chains or just one single chain?

**Comment by martin-steinegger** [comment]
it is encoded based on the single chain

**Comment by Zhu-Siqi** [comment]
> it is encoded based on the single chain

Thanks!
