### ISSUE TITLE
Job kept being stucked in the pending state

### ISSUE THREAD

**Issue by hdahoiowjeasc** [steineggerlab/foldseek#264]
Hi, my job has been stucked in the pending state and I have resubmiited the job for a few time but it didn't help. I ran a few jobs yesterday and everything went on well and the PDB file I submit today is very similar to those submitted yesterday. Don't  know if there is a server deployment or something else. 
I would really appreciate for any replyment.

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## Foldssek Output (for bugs)
Please make sure to also post the complete output of Spacepharer. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute foldseek without any parameters):
* Which foldseek version was used (Statically-compiled, self-compiled, Conda, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by milot-mirdita** [comment]
It might have fallen victim to the deployment steps for Foldseek-Multimer yesterday.

Can you try to change a single character somewhere and resubmit (e.g. some remark line or the last position of any X, Y, Z coordinate or something like that)?

It should make a new cache entry and work again.

If that doesn't work, could you please share the query that is broken?

**Comment by hdahoiowjeasc** [comment]
> It might have fallen victim to the deployment steps for Foldseek-Multimer yesterday.
> 
> Can you try to change a single character somewhere and resubmit (e.g. some remark line or the last position of any X, Y, Z coordinate or something like that)?
> 
> It should make a new cache entry and work again.
> 
> If that doesn't work, could you please share the query that is broken?

I resubmited a job and it is still pending. Previously it should be finished within 1 or 2 min...The previous query id is LBU0UMEo0O6jQzZNkYKQXUr0uAsrbd7O1OC24A. And the resubmitted one is YbZ6VcKIHUFxOujn5BtzlLxyaCZQiqoAgOOe5g.

**Comment by milot-mirdita** [comment]
I found the issue, the AFDB-Proteome returns an empty result list, but that results in an error apparently.

I can leave that DB out for this query, and it should work again. I will try to fix the issue in the meantime.

**Comment by hdahoiowjeasc** [comment]
> I found the issue, the AFDB-Proteome returns an empty result list, but that results in an error apparently.
> 
> I can leave that DB out for this query, and it should work again. I will try to fix the issue in the meantime.

Thank you for your help! I'll wait to see if job can succeed later when the database is left out. And would you please inform me if the problem is fixed?

**Comment by milot-mirdita** [comment]
I fixed the bug, you should be able to submit a new job now with the previously broken query. Thanks a lot!

**Comment by hdahoiowjeasc** [comment]
It worked! Thank you sooo much!
