### ISSUE TITLE
Cannot use createdb to merge two existing db

### ISSUE THREAD

**Issue by pisle0** [steineggerlab/foldseek#269]
I have two large foldseek databases that I want to merge into one database, from the `foldseek createdb` usage, it looks like DB is supported as an input:

`usage: foldseek createdb <i:PDB|mmCIF[.gz]|tar|DB> ... <i:PDB|mmCIF[.gz]|tar|DB> <o:sequenceDB> [options]`

but I run into the following error:
```
Cannot open lookup file .//db_a/db_a_ca.lookup
```
 
To reproduce the error:
```
foldseek createdb ./a ./db_a/db_a
foldseek createdb ./b ./db_b/db_b
foldseek createdb . ./db_ab/db_ab
```

I am interested to know if this is the right way to merge databases, and if not, are there ways to avoid building databases all over again. Thanks!

**Comment by milot-mirdita** [comment]
`concatdbs` is the module you want: https://github.com/steineggerlab/foldseek/issues/79#issuecomment-1519398950

`createdb`'s DB input is intended for a database of PDB/mmCIF/foldcomp files to be converted into sequence+3Di DB. Sorry for the confusion.
