### ISSUE TITLE
200 million unprot database

### ISSUE THREAD

**Issue by jianshu93** [steineggerlab/foldseek#28]
Hello team，

is the newest 200 million uniprot structure by alphafold available？

Thanks，

Jianshu

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## Spacepharer Output (for bugs)
Please make sure to also post the complete output of Spacepharer. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute foldseek without any parameters):
* Which foldseek version was used (Statically-compiled, self-compiled, Conda, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by milot-mirdita** [comment]
If nothing goes wrong, we will be able to make the database available later today.

**Comment by milot-mirdita** [comment]
The database is available to download in Foldseek 3-915ef7d.
