### ISSUE TITLE
Error: target createdb died

### ISSUE THREAD

**Issue by calvincicha** [steineggerlab/foldseek#29]
While running foldseek easy-search I ran into the following error.

##installed foldseek
 conda install -c conda-forge -c bioconda foldseek

##installed database
foldseek databases Alphafold/Proteome afdb tmp 

##try to run easysearch
foldseek easy-search /home/z76r142/AlphaFold/models/SLA-04_01093-RD/ranked_1.pdb /home/z76r142/condaenv/ 1093.m8 tmpfolder

##easy search results in following error

MMseqs2 was not compiled with zlib support. Cannot read compressed input.
Error: target createdb died

## Your Environment
foldseek Version: 2.8bd520
MMseqs2 Version: 13.45111

**Comment by milot-mirdita** [comment]
Bioconda is not updated yet. Please download the binaries from:
https://github.com/steineggerlab/foldseek/releases/tag/3-915ef7d

**Comment by ArnNag** [comment]
Getting the same error without bioconda install. 

Distribution: Ubuntu 22.04 LTS

$ [ $(uname -m) = "x86_64" ] && echo "64bit: Yes" || echo "64bit: No"
grep -q avx2 /proc/cpuinfo && echo "AVX2: Yes" || echo "AVX2: No"
grep -q sse4_1 /proc/cpuinfo && echo "SSE4.1: Yes" || echo "SSE4.1: No"
# for very old systems which support neither SSE4.1 or AVX2
grep -q sse2 /proc/cpuinfo && echo "SSE2: Yes" || echo "SSE2: No"
64bit: Yes
AVX2: Yes
SSE4.1: Yes
SSE2: Yes

$ wget https://github.com/steineggerlab/foldseek/releases/download/3-915ef7d/foldseek-linux-avx2.tar.gz

$ tar xvzf foldseek-linux-avx2.tar.gz

$ foldseek/bin/foldseek createdb ~/Downloads/pdbstyle-sel-gs-bib-40-2.08.tgz astral40db
createdb /home/user/Downloads/pdbstyle-sel-gs-bib-40-2.08.tgz astral40db 

MMseqs Version:         915ef7ddce1bd77080208eff8a434c0985ae7492
Chain name mode         0
Write lookup file       1
Tar Inclusion Regex     .*
Tar Exclusion Regex     ^$
Threads                 8
Verbosity               3

Output file: astral40db
MMseqs2 was not compiled with zlib support. Cannot read compressed input.

**Comment by johnnytam100** [comment]
Same error here.

**Comment by milot-mirdita** [comment]
Bioconda should be up to date now. Can you try if that version works? I have to investigate what’s wrong with the precompiled binaries.

**Comment by johnnytam100** [comment]
Re-created a conda environment and installed foldseek with
`conda install -c conda-forge -c bioconda foldseek`
Still getting the error, as follows:

```
easy-search AF-A0A0G2KTI4-F1-model_v2_AFCT-OUT_single_A130-1136.pdb /data/cltam/script/foldseek/database/ foldseek_aln.m8 tmpFolder 

MMseqs Version:              	3.915ef7d
Seq. id. threshold           	0
Coverage threshold           	0
Coverage mode                	0
Max reject                   	2147483647
Max accept                   	2147483647
Add backtrace                	false
TMscore threshold            	0.5
TMalign fast                 	1
Preload mode                 	0
Threads                      	128
Verbosity                    	3
Substitution matrix          	aa:3di.out,nucl:3di.out
Alignment mode               	3
Alignment mode               	0
E-value threshold            	0.001
Min alignment length         	0
Seq. id. mode                	0
Alternative alignments       	0
Max sequence length          	65535
Compositional bias           	1
Compositional bias           	1
Gap open cost                	aa:10,nucl:10
Gap extension cost           	aa:1,nucl:1
Compressed                   	0
Seed substitution matrix     	aa:3di.out,nucl:3di.out
Sensitivity                  	9.5
k-mer length                 	6
k-score                      	seq:2147483647,prof:2147483647
Max results per query        	1000
Split database               	0
Split mode                   	2
Split memory limit           	0
Diagonal scoring             	true
Exact k-mer matching         	0
Mask residues                	0
Mask residues probability    	0.99995
Mask lower case residues     	0
Minimum diagonal score       	15
Spaced k-mers                	1
Spaced k-mer pattern         	
Local temporary path         	
Alignment type               	2
Remove temporary files       	true
MPI runner                   	
Force restart with latest tmp	false
Chain name mode              	0
Write lookup file            	1
Tar Inclusion Regex          	.*
Tar Exclusion Regex          	^$
Alignment format             	0
Format alignment output      	query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits
Database output              	false

createdb /data/cltam/script/foldseek/database/ tmpFolder/1910639421338238365/target --chain-name-mode 0 --write-lookup 1 --tar-include '.*' --tar-exclude '^$' --threads 128 -v 3 

Output file: tmpFolder/1910639421338238365/target
Error: target createdb died
```

**Comment by milot-mirdita** [comment]
There is a file name missing in this path:
`/data/cltam/script/foldseek/database/`
That looks like a directory. You need to point it to a database.

**Comment by ArnNag** [comment]
The issue seems to be resolved after installing the new conda package

**Comment by johnnytam100** [comment]
Solved! My silly mistake. Thanks!

**Comment by calvincicha** [comment]
Reinstalling with conda worked for me! thanks
