### ISSUE TITLE
What is the different between the three type of afdb？

### ISSUE THREAD

**Issue by genomicsgroup** [steineggerlab/foldseek#30]
Dear foldseek developers

I’m glad to hear that the newly updated Alphafold 210M database is now avaliable for foldseek , but there are three type of the afdb ([afdb.tar.gz](https://foldseek.steineggerlab.workers.dev/afdb.tar.gz)/
[afdb50.tar.gz](https://foldseek.steineggerlab.workers.dev/afdb50.tar.gz)/
[afdb_ca.tar.gz](https://foldseek.steineggerlab.workers.dev/afdb_ca.tar.gz))
I learned that afdb50 was the product of Alphafold 210M db clusted by mmseqs , but what the difference between the other dbs? please help me explain this problem , THX!

**Comment by milot-mirdita** [comment]
afdb.tar.gz and afdb_ca.tar.gz are part of the same database (full 214M afdb). The C-alpha atoms are quite huge though and unnecessary if one does not use the TMalign mode. We split this to allow running only the 3di alignments with a much smaller database.

afdb50 contains the structures picked from the cluster representatives resulting from an MMseqs2 clustering at 50% seq.id and 80% bi-directional coverage.

**Comment by genomicsgroup** [comment]
@milot-mirdita thanks! that help a lot!

**Comment by mlnance** [comment]
@milot-mirdita  Where can I find detailed information on the outputs generated after running `foldseek databases Alphafold/UniProt afdb tmp`? I understand that this command downloads the AlphaFold structure database for me, but I do not know how to interpret, read, and/or use all the resulting files:
`afdb   afdb_ca.tar.gz  afdb_h.index  afdb_ss  afdb_taxonomy   afdb_ca   afdb.dbtype   afdb.index   afdb_ss.dbtype   afdb_ca.dbtype   afdb_h.dbtype   afdb.lookup   afdb_ss.index   afdb_ca.index  afdb_h   afdb_mapping   afdb.tar.gz`

**Comment by jacob-Iuo** [comment]
@mlnance I use the afdb file as the database of foldseek searches! the foldseek easysearch documentation is great for further info on how to use these file outputs
