### ISSUE TITLE
Foldseek easy-search stops on different errors when using --format-output values of "alntmscore,lddt,prob"

### ISSUE THREAD

**Issue by vmkhot** [steineggerlab/foldseek#305]
Hi there! 

Thanks for this great tool - it is my first time using it (also beginner with protein structures)

I created by own prostT5 database from 345 AA seqs by doing this: 
```
foldseek databases ProstT5 weights tmp
foldseek createdb mixed_cluster_0.fa db --prostt5-model weights
```
When I run:
```
foldseek easy-search ../aa_files_mixedclusters/mixed_cluster_0.fa db result.m8 tmp --prostt5-model weights
```
I get the expected result of a tabular "blast like" file

However, I wanted to more informative parameters on my alignments but they all lead to different errors. 

```
foldseek easy-search ../aa_files_mixedclusters/mixed_cluster_0.fa db mixed_cluster_0_result_6.m8 tmp --prostt5-model weights --format-output "query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,qcov,alntmscore,lddt,prob"

```
![image](https://github.com/steineggerlab/foldseek/assets/50498740/edd8906b-e91f-4541-b533-80dc02c8ea05)

and if I run:
```
foldseek easy-search ../aa_files_mixedclusters/mixed_cluster_0.fa db mixed_cluster_0_result_6.m8 tmp --prostt5-model weights --format-output "query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,qcov,alntmscore,lddt"

#OR

foldseek easy-search ../aa_files_mixedclusters/mixed_cluster_0.fa db mixed_cluster_0_result_6.m8 tmp --prostt5-model weights --format-output "query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,qcov,alntmscore"
```

![image](https://github.com/steineggerlab/foldseek/assets/50498740/6ce5b80f-f666-41e8-b7cb-207b4d15511e)

I'm wondering if it's possible to get tmscores and other structural alignment values for 3Di sequences produced from prostt5/AA sequences instead of protein structures? Or if there's a different cause of this error?

Thanks in advance for your help!

Varada

Additionally, I get the following warning in my log (below) and was wondering how this impacts my results/how to solve it? 

```
Cannot find query C-alpha or db C-alpha database
Disabling --sort-by-structure-bits
This impacts the final score and ranking of hits, but not E-values themselves. Ranking alterations primarily occur for E-values < 10^-1.
```

**Comment by milot-mirdita** [comment]
ProstT5 can’t be combined with scores that require structure information, since there is only 3Di tokens and no backbone coordinates.

**Comment by KyrieYsPKU** [comment]
Exec format error
