### ISSUE TITLE
foldseek easy-search ERROR

### ISSUE THREAD

**Issue by YueZhou-oh** [steineggerlab/foldseek#310]
I run foldseek esay-search and get following output, is it the problem of PDB database?

## Steps to Reproduce (for bugs)
foldseek/bin/foldseek easy-search sample_1.pdb pdb100.tar.gz aln tmpFolder2

## Foldssek Output (for bugs)
Create directory tmpFolder2
easy-search sample_1.pdb pdb100.tar.gz aln tmpFolder2 

MMseqs Version:                 bc212bc8602ef426c7b58368c65dd744443f802c
Seq. id. threshold              0
Coverage threshold              0
Coverage mode                   0
Max reject                      2147483647
Max accept                      2147483647
Add backtrace                   false
TMscore threshold               0
TMalign hit order               0
TMalign fast                    1
Preload mode                    0
Threads                         96
Verbosity                       3
LDDT threshold                  0
Sort by structure bit score     1
Alignment type                  2
Exact TMscore                   0
Substitution matrix             aa:3di.out,nucl:3di.out
Alignment mode                  3
Alignment mode                  0
E-value threshold               10
Min alignment length            0
Seq. id. mode                   0
Alternative alignments          0
Max sequence length             65535
Compositional bias              1
Compositional bias              1
Gap open cost                   aa:10,nucl:10
Gap extension cost              aa:1,nucl:1
Compressed                      0
Seed substitution matrix        aa:3di.out,nucl:3di.out
Sensitivity                     9.5
k-mer length                    6
Target search mode              0
k-score                         seq:2147483647,prof:2147483647
Max results per query           1000
Split database                  0
Split mode                      2
Split memory limit              0
Diagonal scoring                true
Exact k-mer matching            0
Mask residues                   0
Mask residues probability       0.99995
Mask lower case residues        1
Minimum diagonal score          30
Selected taxa                
Spaced k-mers                   1
Spaced k-mer pattern         
Local temporary path         
Exhaustive search mode          false
Prefilter mode                  0
Search iterations               1
Remove temporary files          true
MPI runner                   
Force restart with latest tmp   false
Cluster search                  0
Path to ProstT5              
Chain name mode                 0
Write mapping file              0
Mask b-factor threshold         0
Coord store mode                2
Write lookup file               1
Input format                    0
File Inclusion Regex            .*
File Exclusion Regex            ^$
Alignment format                0
Format alignment output         query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits
Database output                 false
Greedy best hits                false

createdb sample_1.pdb tmpFolder2/16899738066533787672/query --chain-name-mode 0 --write-mapping 0 --mask-bfactor-threshold 0 --coord-store-mode 2 --write-lookup 1 --input-format 0 --file-include '.*' --file-exclude '^$' --threads 96 -v 3 

Output file: tmpFolder2/16899738066533787672/query
[=================================================================] 100.00% 1 eta -
Time for merging to query_ss: 0h 0m 0s 3ms
Time for merging to query_h: 0h 0m 0s 2ms
Time for merging to query_ca: 0h 0m 0s 2ms
Time for merging to query: 0h 0m 0s 2ms
Ignore 0 out of 1.
Too short: 0, incorrect: 0, not proteins: 0.
Time for processing: 0h 0m 0s 78ms
createdb pdb100.tar.gz tmpFolder2/16899738066533787672/target --chain-name-mode 0 --write-mapping 0 --mask-bfactor-threshold 0 --coord-store-mode 2 --write-lookup 1 --input-format 0 --file-include '.*' --file-exclude '^$' --threads 96 -v 3 

Output file: tmpFolder2/16899738066533787672/target
[=================================================================] 100.00% 1 eta -
Time for merging to target_ss: 0h 0m 0s 5ms
Time for merging to target_h: 0h 0m 0s 3ms
Time for merging to target_ca: 0h 0m 0s 3ms
Time for merging to target: 0h 0m 0s 2ms
Reordering by identifier
Time for merging to target_h: 0h 0m 0s 2ms
Time for merging to target_ss: 0h 0m 0s 2ms
Time for merging to target_ca: 0h 0m 0s 2ms
Time for merging to target: 0h 0m 0s 2ms

**No structures found in given input.
Error: target createdb died**

**Comment by milot-mirdita** [comment]
Please use the `foldseek databases` workflow to download and setup the database correctly

**Comment by YueZhou-oh** [comment]
> Please use the `foldseek databases` workflow to download and setup the database correctly

I got connection timeout `curl: (7) Failed to connect to foldseek.steineggerlab.workers.dev port 443: Connection timed out` with `foldseek databases`.

So, I have to download pdb100.tar.gz manually. 
Is there any solution/source-code to setup the database  based on the downloaded data.

**Comment by martin-steinegger** [comment]
You could just untar the file and use the db.

tar xvfz pdb100.tar.gz
foldseek easy-search query.pdb pdb aln tmp

**Comment by YueZhou-oh** [comment]
> You could just untar the file and use the db.
> 
> tar xvfz pdb100.tar.gz foldseek easy-search query.pdb pdb aln tmp

I untar the file and got some errors like  `Cannot open lookup file pdb/pdb_ca.lookup!`

```
Output file: tmpFolder2/15273033197155065009/query
[=================================================================] 100.00% 1 eta -
Time for merging to query_ss: 0h 0m 0s 3ms
Time for merging to query_h: 0h 0m 0s 2ms
Time for merging to query_ca: 0h 0m 0s 2ms
Time for merging to query: 0h 0m 0s 2ms
Ignore 0 out of 1.
Too short: 0, incorrect: 0, not proteins: 0.
Time for processing: 0h 0m 0s 74ms
createdb pdb tmpFolder2/15273033197155065009/target --chain-name-mode 0 --write-mapping 0 --mask-bfactor-threshold 0 --coord-store-mode 2 --write-lookup 1 --input-format 0 --file-include '.*' --file-exclude '^$' --threads 96 -v 3 

Output file: tmpFolder2/15273033197155065009/target
[=================================================================] 100.00% 294.85K 21s 651ms      
Cannot open lookup file pdb/pdb_ca.lookup!
Error: target createdb died
```
I see the existing softlink of `xx.lookup` as follows.

```
# cd pdb
# ll *.lookup
-rw-r--r-- 1 root root 45456728 Apr 14 16:06 pdb.lookup
lrwxrwxrwx 1 root root       10 Apr 14 16:06 pdb_seq.lookup -> pdb.lookup
```

So, I add similar soft links for other files.
```
# ln -s pdb.lookup pdb_ca.lookup
# ln -s pdb.lookup pdb_clu.lookup
# ln -s pdb.lookup pdb_h.lookup
# ln -s pdb.lookup pdb_seq_ca.lookup
# ln -s pdb.lookup pdb_seq_h.lookup
# ln -s pdb.lookup pdb_seq_ss.lookup
# ln -s pdb.lookup pdb_ss.lookup
# ll *.lookup
-rw-r--r-- 1 root root 45456728 Apr 14 16:06 pdb.lookup
lrwxrwxrwx 1 root root       10 Jul 23 18:54 pdb_ca.lookup -> pdb.lookup
lrwxrwxrwx 1 root root       10 Jul 23 18:54 pdb_clu.lookup -> pdb.lookup
lrwxrwxrwx 1 root root       10 Jul 23 18:54 pdb_h.lookup -> pdb.lookup
lrwxrwxrwx 1 root root       10 Apr 14 16:06 pdb_seq.lookup -> pdb.lookup
lrwxrwxrwx 1 root root       10 Jul 23 18:54 pdb_seq_ca.lookup -> pdb.lookup
lrwxrwxrwx 1 root root       10 Jul 23 18:54 pdb_seq_h.lookup -> pdb.lookup
lrwxrwxrwx 1 root root       10 Jul 23 18:54 pdb_seq_ss.lookup -> pdb.lookup
lrwxrwxrwx 1 root root       10 Jul 23 18:55 pdb_ss.lookup -> pdb.lookup
```

Then, I run `foldseek easy-search sample_1.pdb pdb100.tar.gz aln tmpFolder2` again, but get same error as follows.
```
createdb pdb tmpFolder2/15273033197155065009/target --chain-name-mode 0 --write-mapping 0 --mask-bfactor-threshold 0 --coord-store-mode 2 --write-lookup 1 --input-format 0 --file-include '.*' --file-exclude '^$' --threads 96 -v 3 

Output file: tmpFolder2/15273033197155065009/target
[=================================================================] 100.00% 294.85K 20s 54ms       
[=================================================================] 100.00% 294.85K 21s 530ms      
[=================================================================] 100.00% 294.85K 23s 61ms       
[=================================================================] 100.00% 294.85K 24s 558ms      
[=================================================================] 100.00% 294.85K 25s 914ms      
Time for merging to target_ss: 0h 0m 0s 2ms
Time for merging to target_h: 0h 0m 0s 2ms
Time for merging to target_ca: 0h 0m 0s 2ms
Time for merging to target: 0h 0m 0s 2ms
Reordering by identifier
Time for merging to target_h: 0h 0m 0s 3ms
Time for merging to target_ss: 0h 0m 0s 3ms
Time for merging to target_ca: 0h 0m 0s 4ms
Time for merging to target: 0h 0m 0s 5ms
No structures found in given input.
Error: target createdb died
```

**Comment by martin-steinegger** [comment]
You can’t search against the tar file. Your second command searches pdb100.tar.gz not the pdb.

**Comment by YueZhou-oh** [comment]
> You can’t search against the tar file. Your second command searches pdb100.tar.gz not the pdb.

sorry that I pasted wrong command in previous reply (I have fixed that).

I did do the search on pdb/ folder and got the same error.

**Comment by martin-steinegger** [comment]
The command should point to the database not a folder. In your command this `pdb/` is interpreted as folder.
Use the following path instead `/path/to/db/pdb`.

**Comment by YueZhou-oh** [comment]
> The command should point to the database not a folder. In your command this `pdb/` is interpreted as folder. Use the following path instead `/path/to/db/pdb`.

Thanks so much! The problem is solved. (maybe the tutorial `foldseek easy-search example/d1asha_ example/ aln tmpFolder` in README misleads me to provide the database folder.)
I run `foldseek easy-search sample_1.pdb pdb/pdb result.m8 tmpFolder2` and got nothing in `result.m8`, does that mean that no hits found in the database?

```
# foldseek easy-search sample_1.pdb pdb/pdb result.m8 tmpFolder2
easy-search sample_1.pdb pdb/pdb result.m8 tmpFolder2 

MMseqs Version:                 bc212bc8602ef426c7b58368c65dd744443f802c
Seq. id. threshold              0
Coverage threshold              0
Coverage mode                   0
Max reject                      2147483647
Max accept                      2147483647
Add backtrace                   false
TMscore threshold               0
TMalign hit order               0
TMalign fast                    1
Preload mode                    0
Threads                         96
Verbosity                       3
LDDT threshold                  0
Sort by structure bit score     1
Alignment type                  2
Exact TMscore                   0
Substitution matrix             aa:3di.out,nucl:3di.out
Alignment mode                  3
Alignment mode                  0
E-value threshold               10
Min alignment length            0
Seq. id. mode                   0
Alternative alignments          0
Max sequence length             65535
Compositional bias              1
Compositional bias              1
Gap open cost                   aa:10,nucl:10
Gap extension cost              aa:1,nucl:1
Compressed                      0
Seed substitution matrix        aa:3di.out,nucl:3di.out
Sensitivity                     9.5
k-mer length                    6
Target search mode              0
k-score                         seq:2147483647,prof:2147483647
Max results per query           1000
Split database                  0
Split mode                      2
Split memory limit              0
Diagonal scoring                true
Exact k-mer matching            0
Mask residues                   0
Mask residues probability       0.99995
Mask lower case residues        1
Minimum diagonal score          30
Selected taxa                
Spaced k-mers                   1
Spaced k-mer pattern         
Local temporary path         
Exhaustive search mode          false
Prefilter mode                  0
Search iterations               1
Remove temporary files          true
MPI runner                   
Force restart with latest tmp   false
Cluster search                  0
Path to ProstT5              
Chain name mode                 0
Write mapping file              0
Mask b-factor threshold         0
Coord store mode                2
Write lookup file               1
Input format                    0
File Inclusion Regex            .*
File Exclusion Regex            ^$
Alignment format                0
Format alignment output         query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits
Database output                 false
Greedy best hits                false

createdb quant_sample_outputs/17D_07M_2024Y_16h_27m_24s/length_455/sample_5/sample_1.pdb tmpFolder2/4268187106907344171/query --chain-name-mode 0 --write-mapping 0 --mask-bfactor-threshold 0 --coord-store-mode 2 --write-lookup 1 --input-format 0 --file-include '.*' --file-exclude '^$' --threads 96 -v 3 

Output file: tmpFolder2/4268187106907344171/query
[=================================================================] 100.00% 1 eta -
Time for merging to query_ss: 0h 0m 0s 4ms
Time for merging to query_h: 0h 0m 0s 4ms
Time for merging to query_ca: 0h 0m 0s 4ms
Time for merging to query: 0h 0m 0s 4ms
Ignore 0 out of 1.
Too short: 0, incorrect: 0, not proteins: 0.
Time for processing: 0h 0m 0s 79ms
Create directory tmpFolder2/4268187106907344171/search_tmp
search tmpFolder2/4268187106907344171/query pdb/pdb tmpFolder2/4268187106907344171/result tmpFolder2/4268187106907344171/search_tmp --alignment-mode 3 --comp-bias-corr 1 --gap-open aa:10,nucl:10 --gap-extend aa:1,nucl:1 -s 9.5 -k 6 --mask 0 --mask-prob 0.99995 --remove-tmp-files 1 

prefilter tmpFolder2/4268187106907344171/query_ss pdb/pdb_ss tmpFolder2/4268187106907344171/search_tmp/8379061611544464906/pref --sub-mat 'aa:3di.out,nucl:3di.out' --seed-sub-mat 'aa:3di.out,nucl:3di.out' -s 9.5 -k 6 --target-search-mode 0 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seq-len 65535 --max-seqs 1000 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --comp-bias-corr-scale 0.15 --diag-score 1 --exact-kmer-matching 0 --mask 0 --mask-prob 0.99995 --mask-lower-case 1 --min-ungapped-score 30 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --threads 96 --compressed 0 -v 3 

Query database size: 1 type: Aminoacid
Estimated memory consumption: 2G
Target database size: 294848 type: Aminoacid
Index table k-mer threshold: 78 at k-mer size 6 
Index table: counting k-mers
[=================================================================] 100.00% 294.85K 0s 938ms    
Index table: Masked residues: 493
Index table: fill
[=================================================================] 100.00% 294.85K 0s 532ms    
Index statistics
Entries:          61221412
DB size:          838 MB
Avg k-mer size:   0.956585
Top 10 k-mers
    LVLVVV      65135
    VVLVVV      59077
    SVSVVV      55628
    VVSVVV      49699
    LVVVVV      47083
    SVVVVV      46136
    CVVVVV      24429
    VCVVVV      22233
    VLVVVV      20593
    LVSVVV      19030
Time for index table init: 0h 0m 2s 373ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 78
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 1
Target db start 1 to 294848
[=================================================================] 100.00% 1 eta -

668.435165 k-mers per position
22581407 DB matches per sequence
1 overflows
1000 sequences passed prefiltering per query sequence
1000 median result list length
0 sequences with 0 size result lists
Time for merging to pref: 0h 0m 0s 0ms
Time for processing: 0h 0m 3s 62ms
structurealign tmpFolder2/4268187106907344171/query pdb/pdb tmpFolder2/4268187106907344171/search_tmp/8379061611544464906/pref tmpFolder2/4268187106907344171/search_tmp/8379061611544464906/strualn --tmscore-threshold 0 --lddt-threshold 0 --sort-by-structure-bits 1 --alignment-type 2 --exact-tmscore 0 --sub-mat 'aa:3di.out,nucl:3di.out' -a 0 --alignment-mode 3 --alignment-output-mode 0 --wrapped-scoring 0 -e 10 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 0.5 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:10,nucl:10 --gap-extend aa:1,nucl:1 --zdrop 40 --threads 96 --compressed 0 -v 3 

[=================================================================] 100.00% 1 eta -
Time for merging to strualn: 0h 0m 0s 6ms
Time for processing: 0h 0m 4s 987ms
mvdb tmpFolder2/4268187106907344171/search_tmp/8379061611544464906/strualn tmpFolder2/4268187106907344171/search_tmp/8379061611544464906/aln 

Time for processing: 0h 0m 0s 5ms
mvdb tmpFolder2/4268187106907344171/search_tmp/8379061611544464906/aln tmpFolder2/4268187106907344171/result -v 3 

Time for processing: 0h 0m 0s 5ms
Removing temporary files
rmdb tmpFolder2/4268187106907344171/search_tmp/8379061611544464906/pref -v 3 

Time for processing: 0h 0m 0s 0ms
convertalis tmpFolder2/4268187106907344171/query pdb/pdb tmpFolder2/4268187106907344171/result result.m8 --sub-mat 'aa:3di.out,nucl:3di.out' --format-mode 0 --format-output query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits --translation-table 1 --gap-open aa:10,nucl:10 --gap-extend aa:1,nucl:1 --db-output 0 --db-load-mode 0 --search-type 0 --threads 96 --compressed 0 -v 3 --exact-tmscore 0 

[=================================================================] 100.00% 1 eta -
Time for merging to result.m8: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 55ms
rmdb tmpFolder2/4268187106907344171/result -v 3 

Time for processing: 0h 0m 0s 2ms
rmdb tmpFolder2/4268187106907344171/query -v 3 

Time for processing: 0h 0m 0s 0ms
rmdb tmpFolder2/4268187106907344171/query_h -v 3 

Time for processing: 0h 0m 0s 0ms
rmdb tmpFolder2/4268187106907344171/query_ca -v 3 

Time for processing: 0h 0m 0s 0ms
rmdb tmpFolder2/4268187106907344171/query_ss -v 3 

Time for processing: 0h 0m 0s 0ms
```

```
# du -sh result.m8 
0       result.m8
# cat result.m8 
# 
```

**Comment by milot-mirdita** [comment]
Does the same query find something on the Webserver at search.foldseek.com ?

**Comment by YueZhou-oh** [comment]
No hits either

![image](https://github.com/user-attachments/assets/8709a7f6-d16d-402d-8fbc-5c9c2214316c)

**Comment by YueZhou-oh** [comment]
I crosschecked other queries and got same results between `foldseek easy-search` and Webserver. 
Thanks a lot for your timely reply.
