### ISSUE TITLE
Dataset problem

### ISSUE THREAD

**Issue by maovshao** [steineggerlab/foldseek#32]
## Context
I find some problems in the link you give about Benchmark data and Foldseek databases: http://wwwuser.gwdg.de/~compbiol/foldseek/

1. [pdb.tar.gz](http://wwwuser.gwdg.de/~compbiol/foldseek/pdb.tar.gz) and [scp40pdb.tar.gz](http://wwwuser.gwdg.de/~compbiol/foldseek/scp40pdb.tar.gz). It seems that they are just the same.
2. [scop.fasta](http://wwwuser.gwdg.de/~compbiol/foldseek/scop.fasta) The Fasta file only contains 11209 seqences. While we have 11211 structures(pdbs). Their numbers can't match.

**Comment by martin-steinegger** [comment]
11211 is the correct number. Please ignore the fasta file for now.

**Comment by maovshao** [comment]
Fine. Thanks for your reply. XD
