### ISSUE TITLE
error with web server

### ISSUE THREAD

**Issue by ValWood** [steineggerlab/foldseek#325]
## Current Behavior

I have been trying to search with  a pdb file for a few days.
https://search.foldseek.com/foldmason

I always get the same error:
<img width="1553" alt="Screenshot 2024-08-09 at 12 13 56" src="https://github.com/user-attachments/assets/e1a261a0-cee0-4c6f-8700-2cd5ac8b650e">

can you help (I tied on about 20 different occasions, daytime, evening and weekend)

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## Foldssek Output (for bugs)
Please make sure to also post the complete output of Spacepharer. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute foldseek without any parameters):
* Which foldseek version was used (Statically-compiled, self-compiled, Conda, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by milot-mirdita** [comment]
Could you please post the URL of the failing job?

**Comment by ValWood** [comment]
Hi,

I was using https://search.foldseek.com/foldmason
with a Pdb file, but now I realise I am probably supposed to upload an alignment file, too.

I was hoping there was a way to search with only a structure. Is this possible?

Thanks
Val

**Comment by milot-mirdita** [comment]
You have to use the foldseek search menu option on the left for Foldseek searches. 
<img width="344" alt="Screenshot 2024-08-09 at 21 57 41" src="https://github.com/user-attachments/assets/dc5a233c-f71d-45e4-9c6b-396ad12fb899">

Foldmason is for building multiple structure alignments out of at least two uploaded protein structures. We will add a check that disables the align button if only one structure was uploaded to avoid confusion.

**Comment by ValWood** [comment]
thanks!
