### ISSUE TITLE
foldseek all-vs-all mode fails?

### ISSUE THREAD

**Issue by kwanUm** [steineggerlab/foldseek#33]
I'm running a simple easy-search for a folder against itself (to get the pairwise tm-scores) using the following:

foldseek easy-search --alignment-type 1 --tmscore-threshold 0.0 /some/folder /some/folder aln.m8 tmpFolder 

/some/folder has 3 pdb files in it (all simple, single chain pdb files for proteins of L=100).

Thus, I expected aln.m8 to have 3 * 3 (or 3*2/2) rows in it representing the tmScores for each possible pair. However, the aln.m8 file showed in my case that there are only 6 rows, so some pairs are missing. Setting the sensetivity (-s) flag to 10 increased the number of rows to 8, but some rows are still missing still.

What's the reason not all the pairs appear in aln.m8? What configuration am I missing to enable that?

**Comment by martin-steinegger** [comment]
Could you share the input please?

**Comment by edraizen** [comment]
Hi, I am experiencing this as well. My structure set has 2184 protein fragments and am expecting 2184^2=4,769,856 pairs but the alignment file only has 1,359,280 pairs. This becomes an an issue after clustering, where I would like to align all cluster members to the cluster representative, but many of those alignments don't exist. 

Would I need to do something similar as is done to mmseqs to run all-vs-all? [How to create a fake prefiltering for all-vs-all alignments](https://github.com/soedinglab/MMseqs2/wiki#how-to-create-a-fake-prefiltering-for-all-vs-all-alignments)

**Comment by mrauha** [comment]
Hello! Likewise. I'm doing quite large all-to-all comparisons, would be very nice to use foldseek for this :) TMalign doesn't support outputting the trafo matrix in all-vs-all mode, brute-forcing it with for loops slows things up.


Here are some tests I did, using TMalign as implemented in USalign (TMalign gives same results). The .cif's can be found [here](https://github.com/mrauha/tmscoretest)

Input for foldseek (the latest release, 915ef7ddc)
```
foldseek easy-search dir1 dir2 aln_testi.m8 tmp --alignment-type 1 --tmscore-threshold 0.0 --format-output query,target,alntmscore,u,t
```
and for USalign (Version 20220924)
```
USalign pdb1 pdb2 -m - -fast
```
The tmscore of the US-align results is the one normalized by the length of p2. 

The trafo matrix form TMalign superimposes p1 to p2. Foldseek has a different ordering, but that's an easy issue to surpass. There are some small changes in the values, but nothing too large. 

The tmscore of foldseek baffles me a bit - how is this calculated? For the first pair, the averaged tmscore given by TMalign (-a T flag) is 0.706, so shouldn't be that.



``` 
p1->p2, tmscore, first three elements of rotation matrix, translation vector
Foldseek	7o6y_3->6zkp_A	0.764	[ 0.581  0.532 -0.616]	..	[ 1.107  2.321 -2.996]
Foldseek	6zkp_A->7o6y_3	0.764	[0.581 0.217 0.784]	..	[ 1.202 -3.749 -0.305]
US-align	7o6y_3->6zkp_A	0.722	[0.581 0.214 0.785]	..	[ 1.22  -3.659 -0.253]
US-align	6zkp_A->7o6y_3	0.691	[ 0.581  0.532 -0.616]	..	[ 1.082  2.234 -2.963]

Foldseek	7o6y_3->6g2j_A	-
Foldseek	6g2j_A->7o6y_3	-
US-align	7o6y_3->6g2j_A	0.805	[0.548 0.086 0.832]	..	[ 0.13  -3.173 -0.479]
US-align	6g2j_A->7o6y_3	0.792	[ 0.548  0.629 -0.551]	..	[ 1.661  2.311 -1.488]

Foldseek	6zkp_A->6g2j_A	0.819	[0.99  0.128 0.064]	..	[ 1.443 -0.76   0.138]
Foldseek	6g2j_A->6zkp_A	0.819	[ 0.99  -0.13  -0.058]	..	[-1.519  0.576 -0.199]
US-align	6zkp_A->6g2j_A	0.759	[ 0.99  -0.13  -0.058]	..	[-1.546  0.562 -0.23 ]
US-align	6g2j_A->6zkp_A	0.783	[0.99  0.128 0.064]	..	[ 1.473 -0.749  0.167]
```

**Comment by martin-steinegger** [comment]
We generated something confusing here, which we need to fix. If you use --alignment-type 1 then in the score column is the TMscore normalized by the query length. Using the alntmscore function recompute the TMscore for the aligned regions only.

**Comment by Old-Shatterhand** [comment]
Hi,

I encountered the same problem for a small dataset of proteins (9 kinases, 10 GPCRs, and 10 Cyclophilins). I expected to get `29 * 29 = 841` values but only got `487`.
Then I figured out that the similarity between the three families might be 0 and foldseek might not report these values.
I checked it and indeed, I get high similarities within the families and very few, small values between families where I would assume values around 0 anyway.

Maybe, @kwanUm and @edraizen, you could check for your data if the values foldseek does not report should be close to 0 anyway?
@martin-steinegger, can this explain that behavior?

Best, Roman

**Comment by martin-steinegger** [comment]
Have you tried to use the `--exhaustive-search 1` flag?

**Comment by martin-steinegger** [comment]
@mrauha thank you so much for the repo to reproduce your error. I just tried to run it with foldseek using the following command:

```
foldseek easy-search tmscoretest tmscoretest aln tmp --alignment-type 1 --tmscore-threshold 0.0 --format-output query,target,alntmscore,u,t,ttmscore,qtmscore --exhaustive-search 1 -e inf
```

The output I get is a 3x3, which is expected: 

```
6g2j_A.cif	6g2j_A.cif	1.000E+00	1.000,-0.000,0.000,0.000,1.000,-0.000,0.000,0.000,1.000	0.000,0.000,0.000	1.000E+00	1.000E+00
6g2j_A.cif	7o6y_3.cif	8.334E-01	0.549,0.086,0.831,0.629,0.613,-0.478,-0.551,0.785,0.283	0.134,-3.107,-0.459	8.201E-01	8.334E-01
6g2j_A.cif	6zkp_A.cif	8.194E-01	0.990,-0.130,-0.058,0.128,0.991,-0.048,0.064,0.040,0.997	-1.519,0.576,-0.199	8.194E-01	7.935E-01
6zkp_A.cif	6zkp_A.cif	1.000E+00	1.000,-0.000,0.000,0.000,1.000,-0.000,0.000,0.000,1.000	0.000,0.000,0.000	1.000E+00	1.000E+00
6zkp_A.cif	6g2j_A.cif	8.194E-01	0.990,0.128,0.064,-0.130,0.991,0.040,-0.058,-0.048,0.997	1.443,-0.760,0.138	7.935E-01	8.194E-01
6zkp_A.cif	7o6y_3.cif	7.645E-01	0.581,0.217,0.784,0.532,0.628,-0.568,-0.616,0.747,0.250	1.202,-3.749,-0.305	7.297E-01	7.645E-01
7o6y_3.cif	7o6y_3.cif	1.000E+00	1.000,-0.000,0.000,0.000,1.000,-0.000,0.000,0.000,1.000	0.000,0.000,0.000	1.000E+00	1.000E+00
7o6y_3.cif	6g2j_A.cif	8.334E-01	0.549,0.629,-0.551,0.086,0.613,0.785,0.831,-0.478,0.283	1.627,2.253,-1.468	8.334E-01	8.201E-01
7o6y_3.cif	6zkp_A.cif	7.645E-01	0.581,0.532,-0.616,0.217,0.628,0.747,0.784,-0.568,0.250	1.107,2.321,-2.996	7.645E-01	7.297E-01
```

**Comment by martin-steinegger** [comment]
@Old-Shatterhand is it possible for you to share your example?

**Comment by Old-Shatterhand** [comment]
Hi @martin-steinegger,

sure. You can find them [here](https://github.com/kalininalab/DataSAIL/tree/main/tests/data/pipeline/pdbs) as part of my current project. 
I also tried to run your line from the recent post above, but I couldn't execute it as the output-format strings `ttmscore` and `qtmscore` are unknown to my (latest) FoldSeek installation from [bioconda](https://anaconda.org/bioconda/foldseek). After removing them, the command was executable and the `aln` file contains 841 entries which is expected. 

Therefore, this issue is considered to be solved from my side.

Thank you for your help.
Roman

**Comment by mrauha** [comment]
Likewise – the current version of Foldseek works as expected, thank you!

One quick question: is it possible to do calculate all-vs-all alignment that considers only the unique pairs? As it's now possible to output both q/ttmscore, calculating both A->B and B->A is redundant.

**Comment by martin-steinegger** [comment]
Thank you so much for this blazing fast. 

@Old-Shatterhand cool project! :) 
@mrauha we do not have a way to get unique pairs. 
cigar/qaln/taln is all from TM-align if you use `--alignment-type 1`

**Comment by HeJunhong1107** [comment]
@martin-steinegger 
Hi~，Do the following command arguments also work for the 7di+AA mode？
`--tmscore-threshold 0.0 --exhaustive-search 1 -e inf` 

It runs successfully, but the results of fident do not seem to reflect the actual structural similarity in my cases. for example, the fident of pdb_pair: 7wxw_R and 2r57 is 1.0，but here are their alignments：
![image](https://github.com/user-attachments/assets/b0350e09-f7d7-41af-8826-dd5f56523680)
