### ISSUE TITLE
Clustering AFDB using foldseek e-values?

### ISSUE THREAD

**Issue by hmms117** [steineggerlab/foldseek#34]
Hi

I am looking to reduce the Alphafold indices further. I was wondering if the cluster mode in foldseek can be used to cluster structures further down than X% sequence identities? For example, using the default AA+3Di mode and evalues provided by the pairwise alignments? 

Thanks for an awesome tool 👍

**Comment by martin-steinegger** [comment]
We are working on a real clustering but for now the following is the best you can do: 

```
foldseek createdb example/ db
foldseek search db db aln tmpFolder -c 0.8 
foldseek clust db aln clu
foldseek createtsv db db clu clu.tsv
```

**Comment by hmms117** [comment]
Thanks Martin! I will try that.

Looking forward to the "real" structural clustering. For your technique to work best, I wonder if multi-domain proteins need to be chopped up into separate domains for easier comparison (?)

Thanks!

**Comment by martin-steinegger** [comment]
This really depends on the use case. Foldseek does not break sequence into domains. You can read more about alignment coverage [here](https://github.com/soedinglab/MMseqs2/wiki#how-to-set-the-right-alignment-coverage-to-cluster).
