### ISSUE TITLE
Making Database from a tar file

### ISSUE THREAD

**Issue by Pooryamb** [steineggerlab/foldseek#35]
Dear Foldseek developers,

I wondered if making a foldseek database from a tar file is possible. The total number of structures in the latest alphafold release is more than 200M. My computational server has a limitation that doesn't allow me to have more than 1M files. It would be great if foldseek could make a database from the concatenated files (like tarred files).

**Comment by martin-steinegger** [comment]
Foldseek supports to build database from tar files, as well as zipped tar files or a tar file containing zipped pdb/mmCIF files.
 
In case of the AlphaFold database. We already generated the database and uploaded it to r2. You can download it through the following command: `foldseek databases Alphafold/UniProt uniprot tmp`. We also offer clustered version called `Alphafold/UniProt50`.

**Comment by Pooryamb** [comment]
Thanks for your reply!
