### ISSUE TITLE
foldseek database problem

### ISSUE THREAD

**Issue by lg10is1** [steineggerlab/foldseek#358]
Hi, 
When I use "foldseek databases PDB pdb tmp" to download the PDBdatabase to the local. It reports an ERROR of "CUID#7 - Download aborted. URI=https://foldseek.steineggerlab.workers.dev/pdb100.tar.gz
Exception: [AbstractCommand.cc:340] errorCode=2".
Is there another way to download the precreated databases?
Thank you so much!
Zhen

**Comment by martin-steinegger** [comment]
The link works for me. Where are you located?

**Comment by lg10is1** [comment]
Thank you! I am from China. 
If there is other way to download the databases?

**Comment by lg10is1** [comment]
> The link works for me. Where are you located?

I can download this link "https://foldseek.steineggerlab.workers.dev/pdb100.tar.gz". Does It contain all the files of the database?

**Comment by martin-steinegger** [comment]
Yes it does.

**Comment by xjhzjucas** [comment]
> Yes it does.

Hi martin, I met the same problem in China. I wonder Is there a difference between downloading directly using commands `foldseek databases` and downloading through that website mentioned above? Do external operations such as indexing need to be performed when downloading through the website above?
