### ISSUE TITLE
Hits are not sorted by e_value, and multiple copies of some records exist.

### ISSUE THREAD

**Issue by Pooryamb** [steineggerlab/foldseek#36]
Dear foldseek developers, 

When I search the 2ekj_A against PDB database with the default settings (3Di/AA), in the html output, I find the 2ekj_A as the first hit and I don't see it anymore in the output. But when I download the search results by selecting "Download All", I see 2ekj_A is reported multiple times in the table, with different e-values. 
1st hit:       "job.pdb_A	2ekj_A	100.000	105	0	0	1	105	1	105	3.285E-16	807	105	105"
569th hit:   "job.pdb_A	2ekj_A	100.000	105	0	0	1	105	1	105	9.501E-16	785	105	105"
1121th hit: "job.pdb_A	2ekj_A	100.000	105	0	0	1	105	1	105	4.406E-16	802	105	105"

Why does it happen? I have renamed 2ekj.pdb to 2ekj.txt and attached it.

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## Spacepharer Output (for bugs)
Please make sure to also post the complete output of Spacepharer. You can use gist.github.com for large output.

## Context
[2ekj.txt](https://github.com/steineggerlab/foldseek/files/9334074/2ekj.txt)

Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute foldseek without any parameters):
* Which foldseek version was used (Statically-compiled, self-compiled, Conda, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by martin-steinegger** [comment]
`2ekj.txt` contains multiple model of the same chain. Foldseek searches each of them. 
It seems some of the chains are better alignable than others, resulting in a lower e-value.

**Comment by Pooryamb** [comment]
Thanks for your reply!
