### ISSUE TITLE
The database generated with ProstT5 based on fasta files is incomplete

### ISSUE THREAD

**Issue by chengaoxiang1985** [steineggerlab/foldseek#378]
The database generated with ProstT5 based on fasta files is not complete, at least it does not contain the "XXX_ca" file。If the database is built with the pdb format files as input, there is no problem, the complete database will be generated, including the "XXX_ca" file.A complete database is required, otherwise the structure search will result in an error message that the file "XXX_ca" cannot be found.

**Comment by chengaoxiang1985** [comment]
This is my code to creat the database:
>>foldseek createdb query_data_cgx/QUERY.fasta database_model_cgx/my_database/DB_cgx --prostt5-model database_model_cgx/prostt5-f16-safetensors.

Followging are all the files included in the newly created database:
<img width="439" alt="image" src="https://github.com/user-attachments/assets/430433fc-5905-4ec7-a6e2-b42ae8f8d240">

Followging are all the files included in the database 'pdb100' downloaded from this Github, clearly some XXX_ca files are contained:
![image](https://github.com/user-attachments/assets/2749ff5d-4bf5-44b1-9d4d-015c3c847ec8)

**Comment by chengaoxiang1985** [comment]
找到答案了：
https://github.com/steineggerlab/foldseek/issues/305

**Comment by xjhzjucas** [comment]
> The database generated with ProstT5 based on fasta files is not complete, at least it does not contain the "XXX_ca" file。If the database is built with the pdb format files as input, there is no problem, the complete database will be generated, including the "XXX_ca" file.A complete database is required, otherwise the structure search will result in an error message that the file "XXX_ca" cannot be found.

您好，想问一下您可以通过foldseek databases命令成功下载各个数据库吗？好像有一些墙的问题，不知道能否解决，谢谢！

**Comment by chengaoxiang1985** [comment]
这个问题我们也有，也是翻墙下载后手动上传过去的。

**Comment by xjhzjucas** [comment]
好的感谢！有一个疑问是直接手动上传后，不知道需不需要建索引等其他操作呀？因为感觉foldseek databases命令应该不仅仅是下载文件，不知道您有没有经验

**Comment by chengaoxiang1985** [comment]
可以解压放在任何地方，只要在用的时候放上绝对路径，如果在当前路径下，则以当前路径开头补上下载到的文件的路径即可，完全不影响结果。

**Comment by xjhzjucas** [comment]
好的，感谢您的帮助！

**Comment by xjhzjucas** [comment]
您好，还有一个问题想请教您，我在下载数据库后手动上传，然后尝试运行foldseek easy-search，发现一直存在报错：
命令：
 `foldseek easy-search /mnt/sdb/kk/database/foldseek/PDBfiles/pdbfile/poi.pdb  /mnt/sdb/kk/database/foldseek/afdb_swiss  res  tmp --alignment-type 1 --threads 4`
但是出现报错：
```
Output file: tmp/188741591713018902/target
[==============================================[=================================================================] 542.38K 0s 510ms
Cannot open lookup file /mnt/sdb/xjh/database/foldseek/afdb_swiss/afdb_swissprot_ca.lookup!
Error: target createdb died

```
此时加上绝对路径好像也会出现，不知道您有没有相关的经验，谢谢！
