### ISSUE TITLE
tmscore-threshold doesn't work

### ISSUE THREAD

**Issue by rothita** [steineggerlab/foldseek#38]
Hi,
first, thanks for this amazing tool :)
I tried using the argument '--tmscore-threshold' with some cutoffs (0.25, 0.5, 0.6, 0.75, 0.9) and it seems that I get the same results every time, with tmscore lower than the threashold. 
for example, I run this command:
foldseek easy-search quary_ranked_0.pdb my_db_archaea_db out_archea.txt /tmp/ --format-mode 4 --alignment-type 2 -c 0.7 --cov-mode 0 --format-output query,target,fident,alnlen,alntmscore,evalue,bits,mismatch,gapopen,qstart,qend,tstart,tend,qcov,tcov **--tmscore-threshold 0.6**

and I get this:
query	target	fident	alnlen	**alntmscore**	evalue	bits	mismatch	gapopen	qstart	qend	tstart	tend	qcov	tcov
ranked_0.pdb	AF-Q58952-F1-model_v1.pdb.gz	0.083	274	**4.084E-01**	2.546E-06	280	157	18	33	258	16	243	0.873	0.916
ranked_0.pdb	AF-Q58484-F1-model_v1.pdb.gz	0.115	233	**2.404E-01**	8.810E-06	260	135	13	3	195	6	207	0.745	0.716
...

the values in column 'alntmscore' are smaller than 0.6: 0.408 0.24...

do you know why it is happening?
I am using the linux-sse41 version
Thanks!
itai

**Comment by milot-mirdita** [comment]
This is a bit of a foot-gun. The `--tmscore-threshold` is not taken into account in the 3Di+AA alignment mode (2). If you want to use that you have to use the tmalign alignment mode (1).

In the 3Di+AA mode, you have to filter the result file afterwards (e.g., with awk, etc.)

**Comment by rothita** [comment]
Ok, I had a feeling I'm missing something. Thanks!

**Comment by martin-steinegger** [comment]
I added support for TMscore filtering into 3Di+AA as well. So the flag should work now as expected.

**Comment by rothita** [comment]
> I added support for TMscore filtering into 3Di+AA as well. So the flag should work now as expected.

Amazing, Thanks!
