### ISSUE TITLE
toggle full query button does not work

### ISSUE THREAD

**Issue by morgannprice** [steineggerlab/foldseek#39]
## Expected Behavior
Hitting the "toggle full query" button hides the portion of the query structure that does not align to the target.

## Current Behavior
The button has no effect. (The button for the toggling full target does work.)

## Steps to Reproduce (for bugs)
Expand 1nqg_A (the top pdb100 hit) in
https://search.foldseek.com/result/CkjKZC8aEOSkQc-KtPlzKZQco_oRGaK2mQb5Bg/0#result-1-0)

## Your Environment
Using Chrome 104.0.5112.101 (64-bit) on windows

**Comment by martin-steinegger** [comment]
@gamcil, do you have any idea what the issue is here?

**Comment by martin-steinegger** [comment]
@morgannprice, we changed the behavior of the server view. Now in default, we only show the aligned regions of the structure, and the query/target button visualizes the rest. Does this help you to understand the alignment better?

**Comment by morgannprice** [comment]
Yes, that is nice, thanks!
