### ISSUE TITLE
Command line has too many arguments

### ISSUE THREAD

**Issue by frenkiboy** [steineggerlab/foldseek#4]
With a large database containing many files the base build step dies due to the command line character limit

For example, when trying to build a database of complete AlphaFold output.

Might be nice to enable an input settings file containing .cif / .pdb structures.

**Comment by martin-steinegger** [comment]
How was your program call? It sounds like you are using a `*` as an argument. 
Do not use a `*` and just use the folder name instead.

**Comment by martin-steinegger** [comment]
Did this resolve your issue?
