### ISSUE TITLE
3Di sequences which file after database command

### ISSUE THREAD

**Issue by Ch-rode** [steineggerlab/foldseek#44]
Hello! I just downloaded the PDB databases. I received those files:
pdb                                                                                                                       
pdb_ca                                                                                                                    
pdb_ca.dbtype                                                                                                             
pdb_ca.index                                                                                                              
pdb_h                                                                                                                     
pdb_h.dbtype                                                                                                              
pdb_h.index                                                                                                               
pdb_mapping                                                                                                               
pdb_ss                                                                                                                    
pdb_ss.dbtype                                                                                                             
pdb_ss.index                                                                                                              
pdb_taxonomy                                                                                                              
pdb.dbtype                                                                                                                
pdb.index                                                                                                                 
pdb.lookup                                                                                                                
pdb.md5sum  

I was wondering which one contains the 3Di sequences. 
Thank you

**Comment by martin-steinegger** [comment]
3Di is in `pdb_ss`, `ss` stands for structural sequence.

**Comment by Ch-rode** [comment]
Thank you very much @martin-steinegger 
Do you know how to parse them? the file contains chinese characters
thanks

**Comment by martin-steinegger** [comment]
Its a `\0` byte that sperate entries. One easy way to get rid of the null bytes would be to convert it to a tsv 

```
foldseek prefixid pdb_ss pdb_ss.tsv --tsv 
```
