### ISSUE TITLE
Foldseek server TM-score

### ISSUE THREAD

**Issue by gezmi** [steineggerlab/foldseek#45]
Hi,

I was running a PDB file with foldseek on the swissprot Af models, using TM-align option. I noticed something weird with the listing of the TM-score
![image](https://user-images.githubusercontent.com/13509667/192238745-8a0a8d44-5095-471c-8b5e-dc2029ade52b.png)
(all results: https://search.foldseek.com/result/aZf9k2cw6BPxvcZSqkVczCDixXzPjNd-hhuY8A/0#result-0-0)

As I understood, the 5th column should be the TM-score, however it is not the same as the TM-score written in light blue above the structure. Is this a bug? If not, what is the difference between the 2 TM-scores?

Thank you for looking into this issue!

**Comment by Khaw18** [comment]
Hello Julia,

I was wondering if you had found an answer?
 
Thank you in advance ;)

**Comment by martin-steinegger** [comment]
The TMscore reported in the structural alignment viewer is normalized by the alignment length. While the one reported in the row above is normalized by the query length. 

In the example above, the alignment is longer than the query, so the TMscore is much lower.

**Comment by gezmi** [comment]
Thank you for the explanation! Would it be possible to get rid of such alignments where 2-4 residues are 15-20 residues away from everything else?

**Comment by martin-steinegger** [comment]
Do you mean trimming single residues that have long gaps to conserved blocks?

**Comment by gezmi** [comment]
Yes. Maybe I am wrong, but they seem not that useful, but messes up further processing and TM-scores.

**Comment by martin-steinegger** [comment]
I agree but it is kinda messing with the TMalign alignment. Applying such rules is often a bit dangerous.
