### ISSUE TITLE
--db-output

### ISSUE THREAD

**Issue by sahakyanhk** [steineggerlab/foldseek#51]
Hello,
 
Could you please give a couple of examples with **--db-output** option? I thought it would create an output database containing the search results, but my output is only 2 file: outDB.dbtype, and outDB.index, whereas the index file contains only one line. Did I misunderstand this option or is there something wrong with it?
My idea was to get a searchable output database to run a new search with another query or parameters. Also, it would be helpful to have search restriction options like --gilist or -seqidlist in blast. 

Thanks,
Harut

**Comment by milot-mirdita** [comment]
Do you want to make a subset of the target sequences that were hit by something, or do you want to make a subset of the query sequences that had some hits?

**Comment by sahakyanhk** [comment]
A subset of the target sequences that were hit by something. 

For instance, we run: 
foldseek easy-search 1pdb.pdb pdb output.tsv tmp  

How can I get a new foldseek database containing all hits from output.tsv. My goal is to run a new search in that subset using another query.

**Comment by milot-mirdita** [comment]
You have to use the non-`easy-` workflows for this. Here is a suggestion how to do this search:

```
# replicate easy-search
foldseek createdb 1pdb.pdb querydb
foldseek search querydb pdb result tmp
foldseek convertalis querydb pdb output.tsv 

# turn result database into a format where we can extract the database keys
foldseek prefixid result result.tsv --tsv
# print only the unique database keys into a file
cat result.tsv | awk '{ print $2 }'  | sort -u > target_keys.tsv
# generate subset of the target database
foldseek createsubdb target_keys.tsv pdb pdb_subset

# search against the target subset
foldseek search other_query_db pdb_subset tmp
foldseek convertalis other_query_db pdb_subset output_2.tsv
```

Keep in mind that the 3Di+AA E-value depends on the target database size, thus you will have possibly unrealistic low E-values when you search against the subset. You can output the TM-score in `convertalis` by adding `alntmscore` to `--format-output`. E.g. `--format-output query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,alntmscore`. TM-score is independent from the target database size.

**Comment by sahakyanhk** [comment]
Thanks, Milot. I tried to reproduce what you suggested but got some problems. The generated pdb_subset does not have pdb_subset_ss* files, and the search fails with the "Input pdb_subset_ss does not exist" error. Also, I am wondering why we need

**foldseek convertalis querydb pdb output.tsv** 
and then
**foldseek prefixid result result.tsv --tsv**

Does not the first column of the result file contains the same database keys? 

Besides, foldseek convertalis requires at least 4 input paths, so **foldseek convertalis querydb pdb output.tsv** does not work. I guess it should be **foldseek convertalis querydb pdb result output.tsv**, though in the foldseek help examples, also only 3 paths provided.

**Comment by milot-mirdita** [comment]
Sorry, I wrote the commands down without actually trying them. I fixed them now. 

You can leave out the first `convertalis` if you don't care about the first searches m8 output.

We need to do a pretty roundabout way of doing this procedure for two reasons. We could just extract the second column (the target accession) from convertalis and give that to `createsubdb --id-mode 1`. But there is no actual guarantee that these are unique.

With this procedure we can extract the internal database key and use that to create the subset. Ideally we would do everything with `convertalis --format-output` but qkey and dbkey are not exposed there. I'll add something to expose these two fields when I have time.

**Comment by sahakyanhk** [comment]
Thanks, it works. Looking forward to testing new options!
