### ISSUE TITLE
inconsistency between 3Di sequence length and Aminoacid sequence length for some PDB ids

### ISSUE THREAD

**Issue by Ch-rode** [steineggerlab/foldseek#52]
Hello ! I was playing around with Foldseek and I mapped the encoded structure sequence from the PDB database downloaded from you (pdb_ss.fasta) to their respective aminoacid fasta sequence from PDB, I found inconsistency for 25.000 ids, like the following:

pdb_id_chain	 ss_seq_len	aa_seq_len	
11as_B	            327	             328	
148l_E                 163                   162
155c_A                134                   121
1a16_A                439                   441
1a7a_A                416                   431

The reasons can be multiple like in some structure the CA atom is missing or the amino-acid/sidechain wasn’t well properly defined etc.

I was wondering if it is possible to have or to know where did you retrieve the aminoacid sequences and if you applied some kind of filtering or cleaning. 

Thank you very much !

**Comment by mvankem** [comment]
We use the aa sequences from the PDB files (the amino acid type is stored alongside the structural information), which can also be found in the database:

`foldseek convert2fasta pdb pdb_aa.fasta`

The 3di and aa sequences should always have the same length, therefore there is no filtering etc. performed.
