### ISSUE TITLE
How to generated AlphaFold Swissprot v3 Taxdb ？

### ISSUE THREAD

**Issue by genomicsgroup** [steineggerlab/foldseek#53]
I used to generated the taxdb for Swissprot v3 but using the taxid option will cause the following error
/remote/foldseek_db/swiss-prot/swissprot_mapping is empty. Rerun createtaxdb to recreate taxonomy mapping.

How to generated AlphaFold Swissprot v3 Taxdb ？

**Comment by martin-steinegger** [comment]
Is this still relevant?
