### ISSUE TITLE
Resuming downloads

### ISSUE THREAD

**Issue by Rolando-at-Arzeda** [steineggerlab/foldseek#54]
## DB Download ERROR 

While downloading big databases, would it be possible to resume the download after an ERROR 500 or other connection error ?
I have been trying for several days to complete the download of the full Alphafold/UniProt db .. it seems that the server does not accept the continuing download options and it always fail, with the foldseek program itself or externally with wget. 

Last server error was just now at 91%, after downloading 554.82G !

**Comment by martin-steinegger** [comment]
We changed the R2 worker. Is this fixed now?

**Comment by Rolando-at-Arzeda** [comment]
Yes it is fixed now thank you very much Martin !
