### ISSUE TITLE
createdb ignores all PDB files

### ISSUE THREAD

**Issue by ksteczk** [steineggerlab/foldseek#6]
Command
`foldseek createdb pfamprocessed/ foldseekDB`
directory pfamprocessed contains PDB files in format:

> ATOM      7  CG  LEU     1      41.236  47.777  43.697
> ATOM      9  CD1 LEU     1      42.032  47.298  42.478
> ATOM     13  CD2 LEU     1      39.833  48.166  43.219
> ATOM     17  C   LEU     1      40.159  45.638  46.822
> ATOM     18  O   LEU     1      40.806  45.323  47.828
> ATOM     19  N   SER     2      39.248  44.822  46.297
> ATOM     21  CA  SER     2      38.875  43.515  46.837
> ATOM     23  CB  SER     2      37.869  42.860  45.885

they come from C-I-Tasser pre-computed database of models
https://zhanglab.ccmb.med.umich.edu/C-I-TASSER/pfam/
`ls -1 pfamprocessed/|head
`
> PF00094.pdb
> PF00242.pdb
> PF00257.pdb
> PF00260.pdb
> PF00324.pdb
> PF00336.pdb
> PF00363.pdb
> PF00379.pdb

Program output:
```
createdb pfamprocessed/ foldseekDB

MMseqs Version: GITDIR-NOTFOUND
Threads         128
Verbosity       3


Output file: foldseekDB
[=================================================================] 100.00% 8.27K 0s 209ms
Time for merging to foldseekDB_ss: 0h 0m 0s 2ms
Time for merging to foldseekDB_h: 0h 0m 0s 2ms
Time for merging to foldseekDB_ca: 0h 0m 0s 2ms
Time for merging to foldseekDB: 0h 0m 0s 2ms
Ignore 8266 out of 8266.
Too short: 0, incorrect  8266.
Time for processing: 0h 0m 0s 267ms
```

**Comment by martin-steinegger** [comment]
Thank you for reporting this. It seems like that the files are not valid PDB files. It is missing some auxiliary information. Currently we parse the file with https://github.com/project-gemmi/gemmi so it’s not really in our hand to parse this file.

```
ATOM   5350  CD1 ILE   353      42.612  53.483  69.066
ATOM   5354  C   ILE   353      43.051  52.935  63.950
ATOM   5355  O   ILE   353      42.122  53.382  63.292
ATOM   5356  N   ALA   354      44.280  52.865  63.444
ATOM   5358  CA  ALA   354      44.579  53.217  62.064
ATOM   5360  CB  ALA   354      46.103  53.241  61.866
ATOM   5364  C   ALA   354      43.862  52.332  61.039
```

**Comment by wojdyr** [comment]
Gemmi didn't accept such files because I haven't come across them before. Normally, the lines are longer.
So now I changed it in gemmi and such files can be read.

**Comment by martin-steinegger** [comment]
@wojdyr thank you for the update. We updated to the new Gemmi version. Thank you so much for developing it. 
Do you have a way to read the plddt (pfactor) in Gemmi?

**Comment by wojdyr** [comment]
@martin-steinegger what is plddt? if I google plddt pfactor I get no results.

**Comment by wojdyr** [comment]
I get it now :-)
If pLDDT is stored as B-factor then yes, it's read and can be then accessed as `atom.b_iso`. I haven't tried it, though.

**Comment by martin-steinegger** [comment]
Ups, yes B-factor haha. Thank you so much. I will try to read the plddts using `atom.b_iso` and let you know if all worked out. Happy new year.

**Comment by martin-steinegger** [comment]
@wojdyr `atom.b_iso` is working like a charm. We included a feature to mask regions based on the b-factor.
