### ISSUE TITLE
foldseek afdb50_best database

### ISSUE THREAD

**Issue by guilhemfaure** [steineggerlab/foldseek#63]
Hello,

Do you provide the foldseek AF50_Best (selecting best plddt for each cluster or taking into account AF corrections for the 4% misfolded proteins) available for the standalone version? I can see It is available on the foldseek server (thanks so much), and you mentioned it will be available to download (foldseek databases) on twitter, so I was wondering if it is somewhere I did not find (I looked at https://foldseek.steineggerlab.workers.dev/ but did not find it, afdb50 seems to be the previous version uploaded in August 2022) or if you still plan to do it? That would be awesome! 

Thanks a lot in advance!

**Comment by martin-steinegger** [comment]
Sorry, we will soon update the foldseek database to alphafold v4. Would you still require access to AF50best?

**Comment by guilhemfaure** [comment]
Thanks! Do you still take the best prediction as the cluster representatives in v4? What is the difference b/w v4 and AF50best?

**Comment by martin-steinegger** [comment]
Yes, we still take the best prediction as representatives in v4.
