### ISSUE TITLE
Alignment length is longer than target/query/both

### ISSUE THREAD

**Issue by chanqian18** [steineggerlab/foldseek#65]
In Foldseek outputs, qcov and tcov are the aligned parts of the query and target respectively over length of the sequence. For my use case, it could be useful to have the overlap of the target and query, as I would like to filter for only results where a certain fraction (0.6) of the query is covered by the alignment. In some cases, it seems that the alignment length is longer than the target length (image 1), making the filter qcov>0.6 miss these results. These alignments give high alntmscore, but only align to small regions (perhaps one helix, image 2). Is this an expected behaviour of foldseek? How is alignment length calculated?

![image](https://user-images.githubusercontent.com/67110786/204797685-54fbfa2e-6666-4e24-a908-271189340619.png)

![image](https://user-images.githubusercontent.com/67110786/204797980-64ed6e9d-d1c6-4b22-9cf9-8de97ddce635.png)

## Your Environment'
Foldseek parameters: foldseek search <querydb> <targetdb> <resultfile> temp -s 9 --alignment-type 1 -a

* Which foldseek version was used (Statically-compiled, self-compiled, Conda, etc.): AVX2, staticly compiled, Foldseek version: 8e8cf0baeca517fd797fba330ed3150b555d17e4, release 21/10/22
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): AMD 4500U, support for AVX2/SSE, 8GB RAM
* Operating system and version: WSL on Windows 10

**Comment by chanqian18** [comment]
Attached is a result where alignment length exceeds both, which I forgot to attach in the original post.
![image](https://user-images.githubusercontent.com/67110786/204810550-95e10022-c9c8-4f47-9d69-67f76d0181c3.png)

**Comment by chanqian18** [comment]
I'm working with Christine Orengo and we're trying to do some scans of AlphaFold domains against PDB chains. I am a bit confused about which coverage settings/parameters (-- cov-mode?) to use on Foldseek-TMalign in order to get only hits that cover at least 60% of the domain I use as a query. qcov, as in the original post, doesn't seem to be appropriate to me (as the target is 50 residues, the query is 249 residues, but qcov is 84.7%).

Sorry if i misunderstood any of the documentation. Thank you for your time!

**Comment by martin-steinegger** [comment]
@chanqian18 to annotate the alphafold domains with cath domains I would recommend using

```
foldseek search afdb cath afdb_cath_aln tmp --max-seqs 10000 --cov-mode 1 -c 0.6

```

**Comment by martin-steinegger** [comment]
Yes, `--cov-mode 2 -c 0.6` is right. Did this work for you?
