### ISSUE TITLE
Default sensitivity is 5.7, not 7.5

### ISSUE THREAD

**Issue by bordin89** [steineggerlab/foldseek#7]
## Expected Behavior

The default threshold for sensitivity should be 7.5 as specified in the documentation. 

## Current Behavior

Easy-search by default runs with a -s value of 5.7. Is this intended? Or should this be switched to 7.5 as specified in the documentation?

Thank you!

**Comment by martin-steinegger** [comment]
Thank you! Yes it should `-s 7.5` in default. We will change it.

**Comment by martin-steinegger** [comment]
I changed the default to `-s 9.5`

**Comment by fteufel** [comment]
Hi @martin-steinegger could you tell me more about the sensitivity value - I noted that -h shows that it's supposedly ranging from 1 to 7.5 as in mmseqs2. 
Is 9.5 the maximum ?

**Comment by martin-steinegger** [comment]
The maximum sensitivity of `-s` can be set beyond `9.5`. We adjusted it to achieve maximal performance on our SCOP training set. However, please note that there may be a point where increasing it further may cause a significant slowdown. In such cases, using the `--exhaustive-search` option might be a better alternative.

For more information on this topic, you can check our [preprint](https://www.biorxiv.org/content/10.1101/2022.02.07.479398v4) where we adjusted the sensitivity to achieve the maximum level for our SCOP benchmark.
