### ISSUE TITLE
Question: what is the exact procedure corresponding to easy-search?

### ISSUE THREAD

**Issue by yakomaxa** [steineggerlab/foldseek#71]
Dear foldseek developers, 

Thank you very much for developing a wonderful software for bioinformatics. 

My question is about how to reproduce manually ```easy-search``` command. Usually I use ```easy-search``` command when searching similar structures from db, but I guess the ```easy-search``` is an alias to a certain series of foldseek commands. I now would like to know how to compose the set of commands corresponding to ```easy-search```.

Could you teach me what combination of commands can do the same things with the following command?

``` foldseek easy-search dirPDBfiles TargetDB aln.m8 tmpFolder --alignment-type 1```

Here, dirPDBfiles is a directory that contains a set of PDB files and TargetDB is a pre-composed foldseek database. 

Thank you in advance.

**Comment by milot-mirdita** [comment]
`easy-search` combines `createdb`, `search` and `convertalis`.

```
foldseek easy-search [inputs ...] target_db result.m8
```
becomes:
```
foldseek createdb [inputs ...] query_db
foldseek search query_db target_db res tmp
foldseek convertalis query_db target_db res result.m8
```

Foldseek `search` is the algorithm described in the preprint. It follows a similar strategy to MMseqs2.
First run an initial fast prefiltering stage to reject most non-homologous hits, then use a slow but sensitive algorithm such as Smith-Waterman (or optionally/additionally TM-align in Foldseek).

**Comment by yakomaxa** [comment]
I run the commands and found that the commands ```search``` and  ```convertalis``` were what I was looking for.  I'm going to run each command on different machines for some reasons, and this helps a lot. Thank you very much.
