### ISSUE TITLE
Data & Privacy

### ISSUE THREAD

**Issue by Khaw18** [steineggerlab/foldseek#73]
Hi, 
I have a few wonderings regarding data protection, confidentiality and privacy of the Foldseek webserver.
I would like to know if the "GitHub Privacy Statement" applies to the FoldSeek webserver, and/or if the webserver has a more specific confidentiality/privacy policy ? Would it also be also possible to let me know how long the submitted files are they stored into your servers, and to whom this information is it accessible to ?
Thank you in advance for your help regarding this matter.
Khawla N.

**Comment by martin-steinegger** [comment]
The foldseek server stores search results. So, results are only visible to us or to the user having the right hash. If space becomes an issue, jobs may be deleted, but this is not done on a set schedule. The stored jobs are not used for downstream services or analyzed by us, and the GitHub Privacy Statement does not apply to the server.
