### ISSUE TITLE
What is 'prefilterDB'?

### ISSUE THREAD

**Issue by zkskek321** [steineggerlab/foldseek#76]
Hi, I'm microbiome researcher in South Korea.

First, thank you for great tool!

I want to get tm-score with two different PDB files using 'foldseek tmalign'.
But, there is no description regard to prefilterDB.

So, what is prefilterDB and how can I download or make it?

Please help me.

Thank you.

**Comment by martin-steinegger** [comment]
Thank you @zkskek321 for your kind words. If you're interested in gaining a deeper understanding of the structures behind Foldseek, I would recommend checking out the MMseqs2 documentation, as the underlying database system and many of the algorithms used in Foldseek are similar to those used in MMseqs2. The documentation can be found here: https://github.com/soedinglab/MMseqs2/wiki
