### ISSUE TITLE
Multiple domain matches not reported on full chains

### ISSUE THREAD

**Issue by bordin89** [steineggerlab/foldseek#78]
## Expected Behavior

If a protein chain in a target database has two domains (or more) I'd expect in the output two output lines, one for each.

i.e.

Query structure
- Single-domain protein with an SH2 domain (PDB ID 1lkk) to search 
against a small database with three structures

Target structure database (all AlphaFold-predicted protein structure 
models)
- Another single-domain protein with a single copy of the SH2 domain 
(UniProt accession B2RZ59)
- Multi-domain protein with two copies of the SH2 domain (UniProt 
accession F1N9Y5)
- Protein that has no structural similarity to the SH2 domain, which is 
a G-protein-coupled receptor (GPCR) protein (UniProt accession P18762)

I would expect in my results to have 

1lkk B2RZ59 start stop evalue <etc>
1lkk F1N9Y5 start_1 stop_1 evalue <etc>
1lkk F1N9Y5 start_2 stop_2 evalue <etc>

and not P18762

## Current Behavior

pdb1lkk.ent_A   AF-F1N9Y5-F1-model_v4.pdb       0.287   101     68      0       5       105     13      108     9.142E-08       233
pdb1lkk.ent_A   AF-B2RZ59-F1-model_v4.pdb       0.254   105     77      0       1       105     1       104     8.398E-07       190

This behaviour happens also when swapping query and target db.

AF-F1N9Y5-F1-model_v4.pdb       pdb1lkk.ent_A   0.287   101     68      0       13      108     5       105     5.600E-07       220
AF-B2RZ59-F1-model_v4.pdb       pdb1lkk.ent_A   0.254   105     77      0       1       104     1       105     3.118E-07       188
<EOF>

The current behaviour affects the current version of Foldseek and past versions of it. 

## Steps to Reproduce (for bugs)
The query structure was downloaded from PDB and the target proteins from AlphaFoldDB
The search was tested in various ways.
- easy-search pdb1lkk.ent target_db results.m8 tmp -s 9
- using createdb, followed by search and convertalis
- using TMalign as aligner
- using 3Di+AA (default)

## Your Environment
version 4e9bfb1d1ba08d8015629bc4e4aae3740b91c697
fresh install of foldseek on MacOS
old install on CentOS 915ef7ddce1bd77080208eff8a434c0985ae7492

I'm attaching the structures for reference.

Thanks for all the great work!

[structures.zip](https://github.com/steineggerlab/foldseek/files/10500580/structures.zip)

**Comment by martin-steinegger** [comment]
Did you try to use the parameter `--alt-ali`? This parameter controls the number of alternative alignments reported.
