### ISSUE TITLE
m8 Format fields are different when using TMalign or 3di

### ISSUE THREAD

**Issue by bordin89** [steineggerlab/foldseek#8]
## Expected Behavior

A default run of foldseek search followed by convertalis (or, alternatively, easy-search) outputs an m8 file with columns as follow:

`query target identity alignment_length mismatches gap_openings query_start query_end target_start target_end evalue bitscore
`
i.e.
`3pvlA_A 3pvlA01_A       0.951   207     10      0       1       207     1       207     1.675E-142      487
`

## Current Behavior

Running the same two structures with the `--alignment-type 1` flag turned on to use TMalign returns values that are inconsistent in position and format.

i.e. 
`3pvlA_A 3pvlA01_A       0.048   597     197     0       1       597     1       208     1.000E+00       100
`

It seems that the third column is no longer fident but something different (RMSD?), while the second to last is no longer an evalue but the TMalign score of 1 (in this case) reported in scientific notation. 
Regarding the third column, I can't seem to find an equivalent result on the standalone TMalign output 

TMalign
```
-bash-4.2$ ./TMalign ../data/cath.S20.v4_3_0.chainpdb/3pvlA ../data/cath.S20.v4_3_0.domainpdb/3pvlA01

 *********************************************************************
 * TM-align (Version 20210224): protein structure alignment          *
 * References: Y Zhang, J Skolnick. Nucl Acids Res 33, 2302-9 (2005) *
 * Please email comments and suggestions to yangzhanglab@umich.edu   *
 *********************************************************************

Name of Chain_1: ../data/cath.S20.v4_3_0.chainpdb/3pvlA (to be superimposed onto Chain_2)
Name of Chain_2: ../data/cath.S20.v4_3_0.domainpdb/3pvlA01
Length of Chain_1: 597 residues
Length of Chain_2: 208 residues

Aligned length= 208, RMSD=   0.00, Seq_ID=n_identical/n_aligned= 1.000
TM-score= 0.34841 (if normalized by length of Chain_1, i.e., LN=597, d0=8.55)
TM-score= 1.00000 (if normalized by length of Chain_2, i.e., LN=208, d0=5.37)
(You should use TM-score normalized by length of the reference structure)

(":" denotes residue pairs of d <  5.0 Angstrom, "." denotes other aligned residues)
EEDLSEYKFAKFAATYFQGTTTHSYTRRPLKQPLLYHDDEGDQLAALAVWITILRFMGDLPEPKYHKIPVMTKIYETLGKKTYKRELQALQQGNSMLEDRPTSNLEKLHFIIGNGILRPALRDEIYCQISKQLTHNPSKSSYARGWILVSLCVGCFAPSEKFVKYLRNFIHGGPPGYAPYCEERLRRTFVNGTRTQPPSWLELQATKSKKPIMLPVTFMDGTTKTLLTDSATTARELCNALADKISLKDRFGFSLYIALFDKVSSLGSGSDHVMDAISQCEQYAKEQGAQERNAPWRLFFRKEVFTPWHNPSEDNVATNLIYQQVVRGVKFGEYRCEKEDDLAELASQQYFVDYGSEMILERLLSLVPTYIPDREITPLKNLEKWAQLAIAAHKKGIYAQRRTDSQKVKEDVVNYARFKWPLLFSRFYEAYKFSGPPLPKSDVIVAVNWTGVYFVDEQEQVLLELSFPEIMAVSSSRGTKMMAPSFTLATIKGDEYTFTSSNAEDIRDLVVTFLEGLRKRSKYVVALQDNPNSGFLSFAKGDLIILDHDTGEQVMNSGWANGINERTKQRGDFPTDCVYVMPTVTLPPREIVALVTM
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
EEDLSEYKFAKFAATYFQGTTTHSYTRRPLKQPLLYHDDEGDQLAALAVWITILRFMGDLPEPKYHKIPVMTKIYETLGKKTYKRELQALQQGNSMLEDRPTSNLEKLHFIIGNGILRPALRDEIYCQISKQLTHNPSKSSYARGWILVSLCVGCFAPSEKFVKYLRNFIHGGPPGYAPYCEERLRRTFVNGTRTQPPSWLELQATKS-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Total CPU time is  0.57 seconds
-bash-4.2$
```

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

Foldseek-3di
`./foldseek/bin/foldseek easy-search data/cath.S20.v4_3_0.chainpdb/3pvlA data/cath.S20.v4_3_0.domainpdb/3pvlA01 3pvlA.m8 tmp --alignment-type 1 -c 0.6 --cov-mode 1 -s 9`
Foldseek-TMalign
`./foldseek/bin/foldseek easy-search data/cath.S20.v4_3_0.chainpdb/3pvlA data/cath.S20.v4_3_0.domainpdb/3pvlA01 3pvlA.m8 tmp -c 0.6 --cov-mode 1 -s 9`
TMalign
`TMalign ../data/cath.S20.v4_3_0.chainpdb/3pvlA ../data/cath.S20.v4_3_0.domainpdb/3pvlA01`

I'm attaching both structures for reference. 
[Structures.zip](https://github.com/steineggerlab/foldseek/files/6955724/Structures.zip)

What are the TMalign parameters used by Foldseek so I can crosscheck the results?

Thanks again for all your work on this, it's an amazing piece of software.

**Comment by martin-steinegger** [comment]
In case of the tmalign alignment type (`--alignment-type 1`) we sort the results by the TMscore normalized by query length. We write the TMscore into the e-value(=TMscore) as well as into the score(=TMscore*100) field.
