### ISSUE TITLE
does `--min-seq-id` refer to 3Di or AA ?

### ISSUE THREAD

**Issue by fteufel** [steineggerlab/foldseek#81]
Hi,

I have a simple question. Does the `--min-seq-id` refer to the alignment in the 3Di alphabet or is it computed on the resulting AA alignment?

maybe I missed it, but I can't seem to find it in the wiki. I guess AA would be more intuitive, just making sure.

Thanks!

**Comment by martin-steinegger** [comment]
It is applied on the amino acid’s

**Comment by fteufel** [comment]
Thanks Martin!
