### ISSUE TITLE
How to sort the result corresponding to each query?

### ISSUE THREAD

**Issue by ManlioWu** [steineggerlab/foldseek#85]
Are the results of easy-search sorted by similarity decreasingly? If not, how can I make it?

**Comment by martin-steinegger** [comment]
Yes they are sorted in this way. Depending on what similarity measure you want to use you could replace our `bitScore * sqrt(alnlddt * alntmscore)` by just `alntmscore` or `lddt`.

**Comment by ManlioWu** [comment]
I got it. Thanks a lot!

> Yes they are sorted in this way. Depending on what similarity measure you want to use you could replace our `bitScore * sqrt(alnlddt * alntmscore)` by just `alntmscore` or `lddt`.
