### ISSUE TITLE
Coordinates of alignment on the target structure

### ISSUE THREAD

**Issue by Pooryamb** [steineggerlab/foldseek#86]
Hi,

I have used foldseek to search the alphafold predicted structure of "D6XMN0" against the PDB database. I think the reported aligned region on the target structure does not align with what is expected.

## Expected Behavior
 The alignment start site on the target should be 21.

## Current Behavior
 The alignment start site on the target is 1.

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.
Please search the attached structure against PDB.
The alignment on the hit "3K81_D" starts from 1. 
![image](https://user-images.githubusercontent.com/90681461/219969374-f29df89f-9828-4f20-84ea-7fa8b845cb61.png)

However, if you look at the fasta sequence of the same protein (3K81_D), the started site shows position 21 rather than 1.
![image](https://user-images.githubusercontent.com/90681461/219969423-e27f80cf-0376-4dc5-8738-2ac3c76af08c.png)

I have attached the structure of D6XMN0 and the fasta sequence of 3K81 for ease of use.
[rcsb_pdb_3K81.fasta.txt](https://github.com/steineggerlab/foldseek/files/10777685/rcsb_pdb_3K81.fasta.txt)
[AF-D6XMN0-F1-model_v4.pdb.txt](https://github.com/steineggerlab/foldseek/files/10777686/AF-D6XMN0-F1-model_v4.pdb.txt)

**Comment by martin-steinegger** [comment]
Somehow I can not reproduce the issue. Here is a screenshot of what I find in the server. 
<img width="1199" alt="Screenshot 2023-03-01 at 22 15 16" src="https://user-images.githubusercontent.com/1413571/222149559-9f348aea-f090-4a12-afc1-de1a81d0b833.png">

**Comment by Pooryamb** [comment]
Thanks for your reply.
Please search the attached PDB structure only against the PDB database (PDB100 2201222). The 3rd hit will be 3k81_D and the alignment on the target hit starts with "SVNS", as I showed above. SVNS starts from position 21, however, foldseek reports amino acid 1 as the start of the alignment.

**Comment by Pooryamb** [comment]
I would appreciate it if you could look into what I have asked.

**Comment by martin-steinegger** [comment]
I apologize for not answering earlier. There is a related issue to the one you are facing. You can find more information at https://github.com/steineggerlab/foldseek/issues/91.

The issue stems from not properly accounting for the residue index and unfortunately, there isn't a straightforward method to address this. We discussed the problem and while it isn't easy to solve in the issue. To resolve the problem, you'll need to renumber the residues in the file yourself for now. We read and align each Calpha in the PDB but ignore missing residues.

**Comment by Pooryamb** [comment]
Thanks for your reply.
