### ISSUE TITLE
Alternative `easy-search` inputs

### ISSUE THREAD

**Issue by mitsenkov** [steineggerlab/foldseek#88]
## Context
As quoted from the Readme file "easy-search can search single or multiple query structures formatted in PDB/mmCIF format (flat or .gz) against a target database (example/) of protein structures."

I am currently searching with a number of mmCIF format files against my pre-generated AlphaFoldDB database on my local machine.

## Question
Rather than searching with PDB/mmCIF format files, would it be possible to search with a single protein ID from the pre-generated AlphaFoldDB database against that same database?

**Comment by martin-steinegger** [comment]
You could create a sub-db for protein ID(s). Here is an issue discussing this https://github.com/steineggerlab/foldseek/issues/77
