### ISSUE TITLE
How to read taxonomy from precomputed databases 

### ISSUE THREAD

**Issue by sriramgarg121** [steineggerlab/foldseek#89]
I downloaded the pdb and swissprot databases using the databases command and the program runs flawlessly. I was wondering how to get the taxonomic information for the hits and the fasta sequnces from the databases for further analysis. The "db_taxonomy" file is unreadable. 

Thanks

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## Foldssek Output (for bugs)
Please make sure to also post the complete output of Spacepharer. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute foldseek without any parameters):
* Which foldseek version was used (Statically-compiled, self-compiled, Conda, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by martin-steinegger** [comment]
@sriramgarg121 the easiest way to access the taxonomy information is by using the following fields:
```
taxid       Taxonomical identifier (needs mmseqs tax db)
taxname     Taxon Name (needs mmseqs tax db)
taxlineage  Taxonomical lineage (needs mmseqs tax db)
```
