### ISSUE TITLE
Discrepancy between online and local Foldseek results

### ISSUE THREAD

**Issue by fozhelvacii** [steineggerlab/foldseek#94]
Hi, 

I'm curious about the parameters that the Foldseek online server uses during input searches. Despite trying all the updated databases, I receive distinct hits compared to running Foldseek locally. Any assistance would be greatly appreciated.

Best,
Fatih

**Comment by milot-mirdita** [comment]
We search with the following parameters:
```-k 7 --mask 1 --tmscore-threshold 0.3 --max-seqs 50000 -e 10 -s 9.5 --max-accept 1000```
