### ISSUE TITLE
Searches pending for 4 days

### ISSUE THREAD

**Issue by pweigele** [steineggerlab/foldseek#95]
## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## Foldssek Output (for bugs)
Please make sure to also post the complete output of Spacepharer. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute foldseek without any parameters):
* Which foldseek version was used (Statically-compiled, self-compiled, Conda, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by pweigele** [comment]
I've submitted a few jobs to search.foldseek.com and they've been pending for days now. What they all have in common is taxonomic limitation to Symbiodinium microadriaticum. For example see job: 7FWUpxTFGW73e927KpQbW01UyQZD_DFueA6uKw

**Comment by milot-mirdita** [comment]
They were caught up in the last server deployment. You have to resubmit them.

Jobs should generally never take more than a few minutes at most (and have a maximum time-limit of 1 hour, after which they are automatically canceled).

**Comment by milot-mirdita** [comment]
It's a bug though that they were not marked as failed during the server restart. I have to investigate that.

**Comment by pweigele** [comment]
Great to know, thanks for the speedy explanation! My colleagues and I love
Foldseek-- it's an amazing tool so helpful to our work and the
functionality is so well implemented.

**Comment by milot-mirdita** [comment]
Actually this was just a plain old logic bug. I fixed the issue and will redeploy the server soon.

**Comment by milot-mirdita** [comment]
The issue should be solved now, additionally I cleared the job cache, that should solve resubmitted jobs running into the same error again.

Also thanks so much for the kind words :)
