### ISSUE TITLE
Cannot run foldseek with pre-generated databases 

### ISSUE THREAD

**Issue by LasseMiddendorf** [steineggerlab/foldseek#96]
## Expected Behavior
Easy-search using either the pre-generated PDB or Alphafold/Proteome database

## Current Behavior
I downloaded the PDB and Alphafold/Proteome database with the `foldseek databases` command. The commands were executed fine without any errors. When using the these databases for the `foldseek easy-search` command I received the following error: 

```
createdb ./afdb/ est__temp/7412489378826820776/target --chain-name-mode 0 --mask-bfactor-threshold 0 --coord-store-mode 2 --write-lookup 1 --tar-include '.*' --tar-exclude '^$' --threads 32 -v 3 

Output file: est__temp/7412489378826820776/target
[=================================================================] 100.00% 564.45K 3s 9ms       
Cannot open lookup file ./afdb//afdb_proteome_ca.lookup!
Error: target createdb died
```

I tired to rename the downloaded afdb_proteome_ca, afdb_proteome_h and afdb_proteome_ss  file to afdb_proteome_ca.lookup, afdb_proteome_h.lookup and afdb_proteome_ss.lookup. This solved the previous error, but resulted in the following error in the easy-search command: 

```
prefilter est__temp/7412489378826820776/query_ss est__temp/7412489378826820776/target_ss est__temp/7412489378826820776/search_tmp/5988886017547201860/pref --sub-mat 'aa:3di.out,nucl:3di.out' --seed-sub-mat 'aa:3di.out,nucl:3di.out' -s 9.5 -k 6 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seq-len 65535 --max-seqs 1000 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --comp-bias-corr-scale 0.15 --diag-score 1 --exact-kmer-matching 0 --mask 0 --mask-prob 0.99995 --mask-lower-case 1 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --threads 32 --compressed 0 -v 3 

Query database size: 1 type: Aminoacid
Estimated memory consumption: 977M
Target database size: 0 type: Aminoacid
Index table k-mer threshold: 78 at k-mer size 6 
Index table: counting k-mers
Index table: Masked residues: 0
No k-mer could be extracted for the database est__temp/7412489378826820776/target_ss.
Maybe the sequences length is less than 14 residues.
Error: Kmer matching step died
Error: Search died

```

## Your Environment

foldseek version:
I tried the statically-compiled SSE4.1 built and the foldseek version installed via conda. Errors occur for both versions.

OS and Version:
Ubuntu 22.04.2 LTS

**Comment by jeversbioprodict** [comment]
I'm experiencing the exact same issue, except in my case `pdb_ca.lookup` is missing.

**Comment by jeversbioprodict** [comment]
I think I might know what's up.
When creating the database with a command like:
`foldseek databases PDB pdb tmp`, the lowercase `pdb` is the name of the database, which you should use later on in the easy-search.

So when doing easy-search, use:
`foldseek easy-search EXMP.pdb pdb aln.m8 tmp`, where again, the lowercase `pdb` is the same as the name you used in the above command to install the database. Don't use the path to the folder.

**Comment by LasseMiddendorf** [comment]
Thanks for the suggestion! I tired this, but unfortunately this didn't solve the problem for me. Still receiving the same errors

**Comment by jeversbioprodict** [comment]
And now, if you run the `easy-search` command from the same folder in which you executed the `foldseek databases PDB pdb tmp` command? It downloads it locally in that folder.

**Comment by LasseMiddendorf** [comment]
Thanks this actually solved my problem! From the documentation it was not clear to me that the target database should be the actual file that is created with this name instead of the path that contains all the files that are downloaded with the `foldseek database` command. 

It might be worth to specify this in a more detailed way in the README file

**Comment by amani-acog** [comment]
I got the same issue,
I have downloaded the pregenerated database using:
```foldseek databases PDB db tmp```

And I am trying to run easy-search as:
```foldseek easy-search example/test1_ db result.html tmp --format-mode 5```
I also tried running: ```foldseek easy-search example/test1_ db result.m8 tmp```

But got the error as:
```Output file: tmp/2986744831516625148/target
[=================================================================] 100.00% 294.85K 0s 449ms
Cannot open lookup file db/pdb_ca.lookup!
Error: target createdb died
```
I have checked the files in ```db``` folder but I couldn't find any file named 'pdb_ca.lookup'
